### ISSUE TITLE
Some API bugs on navi3

### ISSUE THREAD

**Issue by Yanxing-Shi** [ROCmSoftwarePlatform/pytorch#1186]
### 🐛 Describe the bug

Hi, I encountered the following errors while using pytorch API on navi3. The main errors are Segmentation fault (core dumped).
- torch.randn
```
import torch

# failure demo
a = torch.randn([1024,256], device="cuda", dtype=torch.float16) # error: Segmentation fault (core dumped)

# successful demo
a = torch.randn([1024,256], dtype=torch.float16)
a = a.cuda()
```
- torch.testing.assert_close
```
import torch

# failure demo
a = torch.tensor([1e0, 1e-1, 1e-2]).cuda()
b = torch.tensor([1e0, 1e-1, 1e-2]).cuda()
torch.testing.assert_close(a, b) # error: Segmentation fault (core dumped)

# successful demo
a = torch.tensor([1e0, 1e-1, 1e-2]).cpu()
b = torch.tensor([1e0, 1e-1, 1e-2]).cpu()
torch.testing.assert_close(a, b)
```
Which pytorch versions support navi3 or can these bugs be fixed?

### Versions

- device
gfx1100(navi3)
- torch
https://download.pytorch.org/whl/rocm5.2/torch-1.13.1%2Brocm5.2-cp38-cp38-linux_x86_64.whl

**Comment by florisdipt** [comment]
This happens for me as well on 6700XT
