### ISSUE TITLE
GPU Not getting detected

### ISSUE THREAD

**Issue by srinivasans74** [ROCmSoftwarePlatform/pytorch#1247]
### 🐛 Describe the bug

I forked Pytorch from GitHub and I followed the following steps

1. conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi
2. git clone --recursive https://github.com/pytorch/pytorch
3. cd pytorch
4. python tools/amd_build/build_amd.py
5. python setup.py install 

I successfully completed the PyTorch build process. However, when I try to run PyTorch, it is unable to detect my AMD GPU. Additionally, PyTorch is unable to assign streams or execute any functions that involve CUDA. This issue is quite perplexing as the GPU-related functionality seems to be completely non-functional.

### Versions

Collecting environment information...
PyTorch version: 1.3
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 0.0.0

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          40
On-line CPU(s) list:             0-39
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 5215 CPU @ 2.20GHz
Stepping:                        5
CPU MHz:                         2200.000
CPU max MHz:                     3400.0000
CPU min MHz:                     1000.0000

Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==1.3
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-include               2023.1.0         h06a4308_46342  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.6           py311ha02d727_1  
[conda] mkl_random                1.2.2           py311ha02d727_1  
[conda] numpy                     1.24.3          py311h08b1b3b_1  
[conda] numpy-base                1.24.3          py311hf175353_1  
[conda] torch                     1.3                      pypi_0    pypi

**Comment by jithunnair-amd** [comment]
@srinivasans74 A few questions:
1. How come your output is showing pytorch 1.3?? PyTorch is currently at version 2.1: https://github.com/pytorch/pytorch/blob/main/version.txt. It sounds like you're installing a very old version of PyTorch by mistake.
2. Which AMD GPU do you have? Can you find the GPU architecture by using `rocminfo | grep gfx` command?

**Comment by srinivasans74** [comment]
I wanted to install an older version since i wanted to make some changes for performing CU masking
  gfx908

**Comment by jithunnair-amd** [comment]
Your AMD GPU arch is supported, but your PyTorch version is no longer supported by latest ROCm. Please use PyTorch 1.11 or newer.

**Comment by srinivasans74** [comment]
> Your AMD GPU arch is supported, but your PyTorch version is no longer supported by latest ROCm. Please use PyTorch 1.11 or newer.

Will using pytorch 2.1 solve this?
Also; should i specify anything here when i run this
python setup.py install

**Comment by jithunnair-amd** [comment]
Please refer to this page for more information on how to install PyTorch for ROCm: https://rocmdocs.amd.com/en/latest/how_to/pytorch_install/pytorch_install.html. 

For building from source, please use something like: `USE_ROCM=1 python3 setup.py install`
