### ISSUE TITLE
[Caffe2][MIOpen] RNN ParamAcessOp segfault

### ISSUE THREAD

**Issue by rohithkrn** [ROCmSoftwarePlatform/pytorch#274]
MIOpen RNN ParamAccess Op segfaults.

**Comment by rohithkrn** [comment]
More Info:
To reproduce this issue, `caffe2/python/operator_test/cudnn_recurrent_test.py` needs to be run. It fails when running `RecurrentParamGet` operator implemented at `caffe2/operators/rnn/hip/recurrent_op_miopen.cc`

**Comment by ashishfarmer** [comment]
Fixed in #319
