### ISSUE TITLE
[Detectron] Incorrect use of max and abs

### ISSUE THREAD

**Issue by ashishfarmer** [ROCmSoftwarePlatform/pytorch#297]
After enabling Detectron files hipification and building in PR #295, there are warnings while building the project from the following files:
sigmoid_focal_loss_op_hip.cc
ps_roi_pool_op_hip.cc
smooth_l1_loss_op_hip.cc
The warnings are because HIP does not overload `max` and `abs` functions. 

Please add appropriate checks `#if defined (__HIP_PLATFORM_HCC__)` and use more specific HIP functions like `fmaxf` and `fabsf`in the corresponding CUDA files.

**Comment by ashishfarmer** [comment]
The incorrect functions would not just cause warnings, but will also result in wrong functional results

**Comment by 7SK** [comment]
Thanks @ashishfarmer , please review the fix

**Comment by 7SK** [comment]
PR is merged, closing the issue
