### ISSUE TITLE
Build error: THCStorage.cu:4:10: fatal error: 'thrust/device_ptr.h' file not found

### ISSUE THREAD

**Issue by clemej** [ROCmSoftwarePlatform/pytorch#306]
## 🐛 Bug

I'm trying to build pytorch for ROCm, and it fails with this log:

> [ 67%] Building CXX object modules/module_test/CMakeFiles/caffe2_module_test_dynamic.dir/module_test_dynamic.cc.o
> [ 67%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o
> [ 67%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state_dlpack.cc.o
> [ 67%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/caffe2_hip_generated_THCStorage.cu.o
> /home/john/git/pytorch-rocmfork/aten/src/THC/THCStorage.cu:4:10: fatal error: 'thrust/device_ptr.h' file not found
> #include <thrust/device_ptr.h>
>          ^~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> /home/john/git/pytorch-rocmfork/aten/src/THC/THCStorage.cu:4:10: fatal error: 'thrust/device_ptr.h' file not found
> #include <thrust/device_ptr.h>
>          ^~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> CMake Error at /opt/rocm/hip/cmake/FindHIP/run_make2cmake.cmake:18 (file):
>   file failed to open for reading (No such file or directory):
> 
>     /home/john/git/pytorch-rocmfork/build/caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/caffe2_hip_generated_THCStorage.cu.o.depend.pre
> 
> 
> CMake Error at caffe2_hip_generated_THCStorage.cu.o.cmake:134 (message):
>   Error generating
>   /home/john/git/pytorch-rocmfork/build/caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/./caffe2_hip_generated_THCStorage.cu.o
> 
> 
> make[2]: *** [caffe2/CMakeFiles/caffe2_hip.dir/build.make:22908: caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/caffe2_hip_generated_THCStorage.cu.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:3395: caffe2/CMakeFiles/caffe2_hip.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> 

## To Reproduce

1. Install ROCm / libraries from apt repo
1. install rocmSPARSE and hipSPARSE from source
1. clone rocm pytorch repo
1. `python3 tools/amd_build/build_pytorch_amd.py`
1. `USE_ROCM=1 python3 setup.py build`

## Expected behavior

I expect pytorch to compile. 

## Environment

Ubuntu 18.10. 
-- Using python found in /usr/bin/python3
HIP VERSION: 1.5.18353

***** Library versions from dpkg *****

hsakmt-roct VERSION: 1.0.9-8-g238782c
hsakmt-roct-dev VERSION: 1.0.9-8-g238782c
hsa-ext-rocr-dev VERSION: 1.1.9-9-ge4ab040
hsa-rocr-dev VERSION: 1.1.9-9-ge4ab040
hcc VERSION: 1.2.18354
hip_base VERSION: 1.5.18353
hip_hcc VERSION: 1.5.18353

***** Library versions from cmake find_package *****

rocrand VERSION: 1.8.1
hiprand VERSION: 1.8.1
rocblas VERSION: 0.14.2.4
miopen VERSION: 1.5.0-e1f0433
miopengemm VERSION: 1.1.5-9547fb9
rocfft VERSION: 0.8.6.0
hipsparse VERSION: 0.1.3.2
rocsparse VERSION: 0.1.3.2
ROCm is enabled.

NOTE: I do NOT have the ubuntu package `libthrust-dev` installed.. if I do, then it fails with other errors saying cuda isn't installed. 

## Additional context

Have at least some rocm demos working on my HP EliteBook 745 G5, Ryzen 5 PRO 2500U. Thought I'd see if I can use pytorch with rocm yet for my ML projects.

**Comment by jithunnair-amd** [comment]
Are you referring to this link for the steps: https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm? You're missing _at least_ 2 steps:
1. installing hip-thrust (mentioned in the Dockerfile in above link)
2. `python tools/amd_build/build_caffe2_amd.py`

**Comment by iotamudelta** [comment]
Lastly, ROCm 1.9.1 does not work for PyTorch yet. You will need 1.9.2 prerelease - I recommend you use the dockerfile that setups the environment properly and follow the instructions listed in the wiki entry posted above.
