### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by iotamudelta** [ROCmSoftwarePlatform/pytorch#31]
Currently, we do not support multi-GPU on ROCm, nor do we assume it works right now. This issue is tracking insights and progress as we are trying to enable this.

**Comment by Jorghi12** [comment]
The development of [RCCL](https://github.com/ROCmSoftwarePlatform/rccl) appears partially functional. Exciting!

**Comment by iotamudelta** [comment]
@sergey-serebryakov We are actively working on adding multi-GPU support. We hope to have news on experimental support soon!

**Comment by sergey-serebryakov** [comment]
@iotamudelta Thank you! Looking forward to it.

**Comment by iotamudelta** [comment]
Closing, mGPU is supported now.
