### ISSUE TITLE
build from source inside docker does not work.

### ISSUE THREAD

**Issue by ubombi** [ROCmSoftwarePlatform/pytorch#329]
## 🐛 Bug

build inside docker does not work.

## To Reproduce

Build from sources section of `./rocm-docs/caffe2-build.md`

**[Dump Gist](https://gist.github.com/ubombi/1c1e75ead7ae46218df651ee2ff842d5)**

error:
```
caffe2/CMakeFiles/caffe2.dir/build.make:4182: recipe for target 'caffe2/CMakeFiles/caffe2.dir/contrib/aten/aten_op.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2.dir/contrib/aten/aten_op.cc.o] Error 254
```

**Comment by iotamudelta** [comment]
@ubombi Please follow these instructions: https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-Caffe2-for-ROCm if you haven't already. Thanks!

**Comment by iotamudelta** [comment]
@ubombi can you confirm that it now works? thanks!

**Comment by iotamudelta** [comment]
Closing issue for now as I assume this to be fixed.
