### ISSUE TITLE
PyTorch Performance Drop for Resnet50 and Resnet101

### ISSUE THREAD

**Issue by Indrashish** [ROCmSoftwarePlatform/pytorch#335]
## 🐛 Bug

We are observing consistent performance drops for Resnet50 and Resnet101 with PyTorch on both Vega20 and MI25. MIOpen commit details below. 

MIOpen Commit Details
commit 74782da0cf9b1dff8ea6dcfe14e450a3531359d1
Author: Daniel Lowell <daniel.lowell@amd.com>
Date:   Mon Dec 17 16:53:33 2018 -0600

    Removed redundant else condition.

## To Reproduce

1. Load up docker image lcskrishna/rocm-pytorch pfl-1.9.2
2. Build and install MIOpen in the docker as per the commit details provided above
3. Run Resnet50 with Batch-size 64
4. Re-build MIOpen with a commit 1 week old (say Dec 12). Try running the same benchmark again

GPU's observed: MI25, Vega20
ROCm Version: 1.9.307, 1.9.211

**Comment by dagamayank** [comment]
@iotamudelta whats the deal with this one? Is this dependent on caching the `workspace-size` fix?

**Comment by iotamudelta** [comment]
@dagamayank correct.

**Comment by mwootton** [comment]
So to be clear.  I am looking for a commit in MIOpen that causes miopenConvolutionForwardGetWorkSpaceSize (+bd + bw) to be horribly slow?  This happened between 12/12 and 12/17?

We were dealing with the slow 'GetWorkSpaceSize slowness issue well before that.

If it's not that issue, what kind of performance drop am I looking for?  I need to know this to confirm repro.

**Comment by iotamudelta** [comment]
No, this will be solved by the caching, I think. The regression seems to align with the larger perf db.

**Comment by mwootton** [comment]
Alright.  I'll just keep an eye on this.  Let's see where things shake out when the wss_caching gets into circulation.

**Comment by dagamayank** [comment]
> Let's see where things shake out when the wss_caching gets into circulation.

@mwootton when do you think this will be ready?

**Comment by mwootton** [comment]
The PR is accepted, merged into ROCm:master, and "cherry picked".  I don't know the average time it takes to merge into pytorch:master from there.  Add to that the latency of whoever is building and testing (weekly?).

I'll kick this issue back to the opener when I see the merge happen.  I assume there is periodic testing happening.  This should not be reproducible in the next cycle.

**Comment by dagamayank** [comment]
@mwootton did you try the fix to check if it makes the performance agnostic of the size of the miopen perf-db? can you report some before/after performance numbers?

**Comment by iotamudelta** [comment]
@dagamayank see https://github.com/ROCmSoftwarePlatform/pytorch/pull/338

**Comment by Indrashish** [comment]
Issue resolved.
