### ISSUE TITLE
Need recipe for integrating custom CUDA kernels

### ISSUE THREAD

**Issue by aurotripathy** [ROCmSoftwarePlatform/pytorch#339]
## 📚 Documentation

The PyTorch-based  [Faster R-CNN model](https://github.com/jwyang/faster-rcnn.pytorch) use a few special CUDA kernels such as NMS, ROI_Pooing, ROI_Align and ROI_Crop. 

The integration steps under CUDA are available [here  ](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/make.sh)

For ROCm integration, I'm guessing the first step is hipification.

`/opt/rocm/hip/bin/hipify-perl nms_cuda_kernel.cu > nms_hip_kernel.cpp `

What's next? PyTorch 1.0 related packaging?
Kindly provide _instructions_ for the rest of the steps for PyTorch 1.0

The instructions that would perhaps replace the code snippets below.

  ` from torch.utils.cpp_extension import CUDAExtension`

I've tried a few things but the above `import `seem hard-wired to CUDA.
   ```
if torch.cuda.is_available() and CUDA_HOME is not None:
        extension = CUDAExtension
        sources += source_cuda
        define_macros += [("WITH_CUDA", None)]
        extra_compile_args["nvcc"] = [
            "-DCUDA_HAS_FP16=1",
            "-D__CUDA_NO_HALF_OPERATORS__",
            "-D__CUDA_NO_HALF_CONVERSIONS__",
            "-D__CUDA_NO_HALF2_OPERATORS__",
        ]

```

```
   ext_modules = [
        extension(
            "model._C",
            sources,
            include_dirs=include_dirs,
            define_macros=define_macros,
            extra_compile_args=extra_compile_args,
        )
    ]
```

**Comment by iotamudelta** [comment]
HIPExtensions have landed upstream, torchvision is ROCm GPU kernel enabled.
