### ISSUE TITLE
Building PyTorch for ROCm instructions

### ISSUE THREAD

**Issue by nsburbank** [ROCmSoftwarePlatform/pytorch#341]
The latest ROCm PyTorch docker image (rocm/pytorch:rocm2.1) appears not to include Boost, resulting in a build failure when following the recommended build process at https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm.

After manually installing Boost, PyTorch builds successfully.

**Comment by iotamudelta** [comment]
Known issue w/ ROCm 2.1 RC1, will be fixed in ROCm 2.1 RC2
