### ISSUE TITLE
Minor format error terminates the unit-test run. 

### ISSUE THREAD

**Issue by aurotripathy** [ROCmSoftwarePlatform/pytorch#345]
## To Reproduce

1. Use option 3 from here https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm

2. In step 5, there's a choice (not sure why)  to use one of two repos. Use the first one. 
`git clone https://github.com/pytorch/pytorch.git` **or** 
`git clone https://github.com/ROCmSoftwarePlatform/pytorch.git `

3. Once built, run the unit-tests with the command below.

`PYTORCH_TEST_WITH_ROCM=1 python test/run_test.py –verbose
`

```
======================================================================
FAIL: test_print (test_torch.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/pytorch/test/test_torch.py", line 8906, in test_print
    self.assertExpectedInline(str(x), '''tensor([1.0000e+28, 1.0000e-28])''')
  File "/data/pytorch/test/expecttest.py", line 195, in assertExpectedInline
    self.assertMultiLineEqual(expect, actual, msg=help_text)
AssertionError: 'tensor([1.0000e+28, 1.0000e-28])' != 'tensor([1.00000e+28, 1.00000e-28])'
- tensor([1.0000e+28, 1.0000e-28])
+ tensor([1.00000e+28, 1.00000e-28])
?               +        +
 : To accept the new output, re-run test with envvar EXPECTTEST_ACCEPT=1 (we recommend staging/committing your changes before doing this)
```

**Comment by iotamudelta** [comment]
There is a choice as we have an upstream and our fork.

This looks to me like an upstream issue.

**Comment by aurotripathy** [comment]
OK, will use the second repo. Thank you.
