### ISSUE TITLE
Does it support for Ubuntu18.04?

### ISSUE THREAD

**Issue by internetchild** [ROCmSoftwarePlatform/pytorch#365]
Does it support for Ubuntu18.04?
If yes, how to build pytorch for Ubuntu18.04? thank you

**Comment by Delaunay** [comment]
I was able to make it work on xubuntu 18.10 on python3.
I posted the rough steps I followed to get it to compile [here][1].
I may have missed some dependencies but it should work.

[1]: https://github.com/ROCmSoftwarePlatform/pytorch/issues/337#issuecomment-467220107

**Comment by iotamudelta** [comment]
@internetchild ROCm itself is supported on Ubuntu 18.04. PyTorch should work but we do not claim any support for it. @Delaunay posted steps to build it on 18.10 which you can follow.

If you look at the upstream CI, ROCm is a build and tested target on Ubuntu 16.04 and CentOS 7.5. If using a docker is acceptable to you, I'd recommend pulling the 16.04 docker on 18.04, I've successfully ran this configuration and am currently using a 18.10 host with the 16.04 docker.
