### ISSUE TITLE
Pytorch / python3

### ISSUE THREAD

**Issue by billwebb** [ROCmSoftwarePlatform/pytorch#373]
## 📚 Documentation

I need to run pytorch with python3, as the projects I need to work on are currently python3 based.

I've tried following these instructions (below) which all provide pytorch for python2. I've made unsuccesful attempts to build pytorch with python3 with no luck. Any suggestions?

https://rocm-documentation.readthedocs.io/en/latest/Deep_learning/Deep-learning.html#recommended-install-using-published-pytorch-rocm-docker-image

https://rocm.github.io/pytorch.html

**Comment by Delaunay** [comment]
I built rocm pytorch with python 3.6.
There is nothing py3 specific to do.

I wrote the rough steps I followed [here][1]

[1]: https://github.com/ROCmSoftwarePlatform/pytorch/issues/337#issuecomment-467220107

**Comment by iotamudelta** [comment]
@billwebb if you want to use docker (which I recommend), please pull `rocm/pytorch:rocm2.1_ubuntu16.04_py3.6`, subsequently, follow the steps in the documentation replacing `python` with `python3.6`.

A few notes: we are not running py3 on the PyTorch CI currently for ROCm. We are using it for some things internally and there are only a few unit test failures specific to 3. If you run into any issues - please file an issue here!

**Comment by billwebb** [comment]
root@f508b0a55dc9:/data/project/pytorch2/pytorch# PYTORCH_TEST_WITH_ROCM=1 python3.6 test/run_test.py --verbose
Traceback (most recent call last):
  File "test/run_test.py", line 16, in <module>
    import torch
  File "/root/.local/lib/python3.6/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: /root/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: _ZN4c10d13syncReductionERSt10shared_ptrINS_12ProcessGroup4WorkEERSt6vectorIN2at6TensorESaIS7_EERS7_

**Comment by iotamudelta** [comment]
@billwebb is this in the docker or on host? We haven't seen this issue in the docker.

**Comment by billwebb** [comment]
This was in the docker.

**Comment by billwebb** [comment]
Just tried it again.. Same results.  Here are the steps I followed -

Running Ubuntu 18.04.1 LTS

docker pull rocm/pytorch:rocm2.1_ubuntu16.04_py3.6

git clone https://github.com/pytorch/pytorch.git
cd pytorch
git submodule init
git submodule update

docker run -it -v $HOME:/data --privileged --rm --device=/dev/kfd --device=/dev/dri --group-add video -p 5000:8888 -p 5001:6006 rocm/pytorch:rocm2.1_ubuntu16.04_py3.6

// from within container

cd /data/pytorch
python3.6 tools/amd_build/build_amd.py

export HCC_AMDGPU_TARGET=gfx900    // using a Vega 64
python3.6 setup.py install

cd
python3.6
Python 3.6.8 (default, Dec 24 2018, 19:24:27) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so: undefined symbol: _ZN4c10d13syncReductionERSt10shared_ptrINS_12ProcessGroup4WorkEERSt6vectorIN2at6TensorESaIS7_EERS7_

**Comment by iotamudelta** [comment]
@billwebb can you not do the export step? We are by default supporting all ROCm architectures in PyTorch now. Please also do
`USE_ROCM=1 USE_LMDB=1 USE_OPENCV=1 python setup.py install`

Also, there is a docker image w/ PyTorch installed available: `docker pull rocm/pytorch:rocm2.2_ubuntu16.04_py3.6_pytorch`

**Comment by billwebb** [comment]
> @billwebb can you not do the `export HCC_AMDGPU_TARGET` step? We are by default supporting all ROCm architectures in PyTorch now. Please also do
> `USE_ROCM=1 USE_LMDB=1 USE_OPENCV=1 python setup.py install`
> 
> Also, there is a docker image w/ PyTorch installed available: `docker pull rocm/pytorch:rocm2.2_ubuntu16.04_py3.6_pytorch`

Thanks.  I am able to o get the docker w/ PyTorch working. But, I need to use Unity and ml-agents with this.  Any suggestions for the best way to do that?

**Comment by billwebb** [comment]
And I've also tried installing the dependencies directly on my machine and building there.  I have hip clearly installed, but the build script isn't finding it..
``
-- Using third party subdirectory Eigen.
Python 3.6.7
-- Found PythonInterp: /usr/bin/python3.6 (found suitable version "3.6.7", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib/libpython3.6m.so.1.0 (found suitable version "3.6.7", minimum required is "2.7") 
-- Could NOT find pybind11 (missing: pybind11_DIR)
-- Could NOT find pybind11 (missing: pybind11_INCLUDE_DIR) 
-- Using third_party/pybind11.
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- MPI support found
-- MPI compile flags: -pthread
-- MPI include path: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI LINK flags path: -pthread
-- MPI libraries: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
CMake Warning at cmake/Dependencies.cmake:665 (message):
  OpenMPI found, but it is not built with CUDA support.
Call Stack (most recent call first):
  CMakeLists.txt:234 (include)


-- Adding OpenMP CXX_FLAGS: -fopenmp
-- Will link against OpenMP libraries: /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- Found HIP: /opt/rocm (found suitable version "1.5.19025", minimum required is "1.0") 
HIP VERSION: 1.5.19025

***** Library versions from dpkg *****

rocm-dev VERSION: 2.1.96
rocm-device-libs VERSION: 0.0.1
rocm-libs VERSION: 2.2.31
hsakmt-roct VERSION: 1.0.9-99-g3ba20ce
hsakmt-roct-dev VERSION: 1.0.9-99-g3ba20ce
hsa-ext-rocr-dev VERSION: 1.1.9-45-ge88639f
hsa-rocr-dev VERSION: 1.1.9-45-ge88639f
hcc VERSION: 1.3.19045
hip_base VERSION: 1.5.19025
hip_hcc VERSION: 1.5.19025

***** Library versions from cmake find_package *****

rocrand VERSION: 1.8.2
hiprand VERSION: 1.8.2
rocblas VERSION: 2.0.1.0
CMake Error at /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
  By not providing "Findhip.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "hip", but
  CMake did not find one.

  Could not find a package configuration file provided by "hip" with any of
  the following names:

    hipConfig.cmake
    hip-config.cmake

  Add the installation prefix of "hip" to CMAKE_PREFIX_PATH or set "hip_DIR"
  to a directory containing one of the above files.  If "hip" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /opt/rocm/miopen/lib/cmake/miopen/miopen-config.cmake:89 (find_dependency)
  cmake/public/LoadHIP.cmake:117 (find_package)
  cmake/public/LoadHIP.cmake:155 (find_package_and_print_version)
  cmake/Dependencies.cmake:785 (include)
  CMakeLists.txt:234 (include)


-- Configuring incomplete, errors occurred!
See also "/home/billw/project/pytorch2/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/billw/project/pytorch2/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 721, in <module>
    build_deps()
  File "setup.py", line 288, in build_deps
    build_dir='build')
  File "/home/billw/project/pytorch2/pytorch/tools/build_pytorch_libs.py", line 246, in build_caffe2
    my_env)
  File "/home/billw/project/pytorch2/pytorch/tools/build_pytorch_libs.py", line 226, in run_cmake
    check_call(cmake_args, cwd=build_dir, env=my_env)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/billw/project/pytorch2/pytorch', '-DBUILDING_WITH_TORCH_LIBS=ON', '-DBUILD_BINARY=False', '-DBUILD_CAFFE2_OPS=True', '-DBUILD_PYTHON=True', '-DBUILD_SHARED_LIBS=ON', '-DBUILD_TEST=True', '-DBUILD_TORCH=ON', '-DCAFFE2_STATIC_LINK_CUDA=False', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_FLAGS= ', '-DCMAKE_C_FLAGS= ', '-DCMAKE_EXE_LINKER_FLAGS=', '-DCMAKE_INSTALL_PREFIX=/home/billw/project/pytorch2/pytorch/torch', '-DCMAKE_PREFIX_PATH=/usr/lib/python3/dist-packages', '-DCMAKE_SHARED_LINKER_FLAGS=', '-DINSTALL_TEST=True', '-DNCCL_EXTERNAL=False', '-DNUMPY_INCLUDE_DIR=/home/billw/.local/lib/python3.6/site-packages/numpy/core/include', '-DONNX_ML=False', '-DONNX_NAMESPACE=onnx_torch', '-DPYTHON_EXECUTABLE=/usr/bin/python3.6', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_LIBRARY=/usr/lib/libpython3.6m.so.1.0', '-DRCCL_INCLUDE_DIR=/opt/rocm/include', '-DRCCL_LIB_DIR=/opt/rocm/lib', '-DRCCL_ROOT_DIR=/opt/rocm/', '-DRCCL_SYSTEM_LIB=/opt/rocm/lib/librccl.so', '-DTHD_SO_VERSION=1', '-DTORCH_BUILD_VERSION=1.1.0a0+aead509', '-DUSE_CUDA=False', '-DUSE_DISTRIBUTED=True', '-DUSE_FBGEMM=True', '-DUSE_FFMPEG=False', '-DUSE_LEVELDB=False', '-DUSE_LMDB=False', '-DUSE_MKLDNN=True', '-DUSE_NCCL=False', '-DUSE_NNPACK=True', '-DUSE_NUMPY=True', '-DUSE_OPENCV=False', '-DUSE_QNNPACK=True', '-DUSE_RCCL=True', '-DUSE_ROCM=True', '-DUSE_SYSTEM_EIGEN_INSTALL=OFF', '-DUSE_SYSTEM_NCCL=False', '-DUSE_TENSORRT=False', '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON']' returned non-zero exit status 1.
billw@scabbers:~/project/pytorch2/pytorch$ hip
hipcc                      hipconvertinplace-perl.sh  hipercdecode               hipify-cmakefile           
hipcc_cmake_linker_helper  hipconvertinplace.sh       hipexamine-perl.sh         hipify-perl                
hipconfig                  hipdemangleatp             hipexamine.sh              hipstopgm                  
billw@scabbers:~/project/pytorch2/pytorch$ hipconfig 
HIP version  : 1.5.19025

== hipconfig
HIP_PATH     : /opt/rocm
HIP_PLATFORM : hcc
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/include -I/opt/rocm/hcc/include

== hcc
HSA_PATH     : /opt/rocm/hsa
HCC_HOME     : /opt/rocm/hcc
HCC clang version 8.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang 683c680a6bff215baa3bd9d3099ba1a43e24cf2e) (ssh://gerritgit/lightning/ec/llvm 6e349ce344586b4254654aea8f34444a13aedb67) (based on HCC 1.3.19045-fea3e2b-683c680-6e349ce )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
LLVM (http://llvm.org/):
  LLVM version 8.0.0svn
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc/include -I/opt/rocm/includeHCC-ldflags  :  -hc -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive

=== Environment Variables
PATH=/home/billw/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin/x86_64:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin/x86_64
HIP_DIR=/opt/rocm/hip

== Linux Kernel
Hostname     : scabbers
Linux scabbers 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
``

**Comment by billwebb** [comment]
Looks like this is being listed as a feature request?

In the mean time, any suggestions how to get around this?

CMake Error at /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
By not providing "Findhip.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "hip", but
CMake did not find one.

Could not find a package configuration file provided by "hip" with any of
the following names:

hipConfig.cmake
hip-config.cmake
Add the installation prefix of "hip" to CMAKE_PREFIX_PATH or set "hip_DIR"
to a directory containing one of the above files. If "hip" provides a
separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
/opt/rocm/miopen/lib/cmake/miopen/miopen-config.cmake:89 (find_dependency)
cmake/public/LoadHIP.cmake:117 (find_package)
cmake/public/LoadHIP.cmake:155 (find_package_and_print_version)
cmake/Dependencies.cmake:785 (include)
CMakeLists.txt:234 (include)

**Comment by iotamudelta** [comment]
@billwebb this looks like the case sensitivity issue we are solving in step 4) of https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm#option-4-install-directly-on-host this by altering the ROCm install. I hope this to be a temporary hack.

**Comment by billwebb** [comment]
> @billwebb this looks like the case sensitivity issue we are solving in step 4) of https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm#option-4-install-directly-on-host this by altering the ROCm install. I hope this to be a temporary hack.

Thanks.  That helps get me further.  Now, seeing this issue.  Any suggestions?

```
[ 94%] Building CXX object caffe2/CMakeFiles/basic.dir/__/aten/src/ATen/test/basic.cpp.o
cd /home/billw/project/pytorch/build/caffe2 && /usr/bin/c++  -DAT_PARALLEL_OPENMP=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DNDEBUG -DONNX_NAMESPACE=onnx_torch -DUSE_C11_ATOMICS=1 -D_FILE_OFFSET_BITS=64 -D_THP_CORE -I/home/billw/project/pytorch/aten/src -I/home/billw/project/pytorch/build -I/home/billw/project/pytorch -I/opt/rocm/miopen/include -isystem /home/billw/project/pytorch/build/third_party/gloo -isystem /home/billw/project/pytorch/cmake/../third_party/gloo -isystem /home/billw/project/pytorch/cmake/../third_party/googletest/googlemock/include -isystem /home/billw/project/pytorch/cmake/../third_party/googletest/googletest/include -I/home/billw/project/pytorch/third_party/protobuf/src -isystem /home/billw/project/pytorch/third_party/gemmlowp -isystem /home/billw/project/pytorch/third_party/neon2sse -I/home/billw/project/pytorch/cmake/../third_party/benchmark/include -isystem /home/billw/project/pytorch/third_party -isystem /usr/include/opencv -isystem /home/billw/project/pytorch/cmake/../third_party/eigen -isystem /usr/include/python3.6m -isystem /home/billw/project/pytorch/cmake/../third_party/pybind11/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem /opt/rocm/hip/include -isystem /opt/rocm/rocblas/include -isystem /opt/rocm/rocfft/include -isystem /opt/rocm/hipsparse/include -isystem /opt/rocm/hiprand/include -isystem /opt/rocm/rocrand/include -isystem /opt/rocm/include -I/home/billw/project/pytorch/build/caffe2/contrib/aten -I/home/billw/project/pytorch/third_party/onnx -I/home/billw/project/pytorch/build/third_party/onnx -I/home/billw/project/pytorch/third_party/foxi -I/home/billw/project/pytorch/build/third_party/foxi -isystem /home/billw/project/pytorch/third_party/ideep/mkl-dnn/include -isystem /home/billw/project/pytorch/third_party/ideep/include -isystem /home/billw/project/pytorch/third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/include -I/home/billw/project/pytorch/build/caffe2/aten/src/TH -I/home/billw/project/pytorch/aten/src/TH -I/home/billw/project/pytorch/build/caffe2/aten/src -I/home/billw/project/pytorch/build/aten/src -I/home/billw/project/pytorch/aten/../third_party/catch/single_include -I/home/billw/project/pytorch/aten/src/ATen/.. -I/home/billw/project/pytorch/build/caffe2/aten/src/ATen -I/home/billw/project/pytorch/caffe2/core/nomnigraph/include -I/home/billw/project/pytorch/third_party/miniz-2.0.8 -I/home/billw/project/pytorch/caffe2/../torch/csrc/api -I/home/billw/project/pytorch/caffe2/../torch/csrc/api/include -I/home/billw/project/pytorch/c10/.. -I/home/billw/project/pytorch/build/third_party/ideep/mkl-dnn/include -I/home/billw/project/pytorch/third_party/ideep/mkl-dnn/src/../include -I/home/billw/project/pytorch/c10/hip/../.. -I/opt/rocm/hcc/include -I/opt/rocm/hsa/include -I/opt/rocm/include/thrust/system/cuda/detail/cub-hip -I/home/billw/project/pytorch/build/third_party/gloo/hip -isystem /home/billw/project/pytorch/third_party/googletest/googletest/include -isystem /home/billw/project/pytorch/third_party/googletest/googletest  -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -fPIE   -DCAFFE2_USE_GLOO -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-unknown-pragmas -Wno-missing-braces -fopenmp -fPIC -D__HIP_PLATFORM_HCC__=1 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 -DHIP_VERSION=1 -Wno-macro-redefined -Wno-inconsistent-missing-override -Wno-exceptions -Wno-shift-count-negative -Wno-shift-count-overflow -Wno-unused-command-line-argument -Wno-duplicate-decl-specifier -DCAFFE2_USE_MIOPEN -DUSE_MIOPEN -std=gnu++11 -o CMakeFiles/basic.dir/__/aten/src/ATen/test/basic.cpp.o -c /home/billw/project/pytorch/aten/src/ATen/test/basic.cpp
cc1plus: warning: command line option ‘-Wno-duplicate-decl-specifier’ is valid for C/ObjC but not for C++
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_place_num'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_partition_num_places'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_partition_place_nums'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_max_task_priority_'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_place_num_procs'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_num_places_'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_place_proc_ids_'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_place_num_procs_'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_partition_place_nums_'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_partition_num_places_'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_max_task_priority'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_place_num_'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_num_places'
../../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so:(*IND*+0x0): multiple definition of `omp_get_place_proc_ids'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/test_parallel.dir/build.make:119: recipe for target 'bin/test_parallel' failed
make[2]: *** [bin/test_parallel] Error 1
make[2]: Leaving directory '/home/billw/project/pytorch/build'
CMakeFiles/Makefile2:5469: recipe for target 'caffe2/CMakeFiles/test_parallel.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/test_parallel.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

**Comment by iotamudelta** [comment]
Unfortunately the output is too short. Could you do a `python setup.py clean`, try to compile again and attach the full compile log here? Thanks!

**Comment by billwebb** [comment]
Build log is attached.
[pytorch-build.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/3242776/pytorch-build.log)


> Unfortunately the output is too short. Could you do a `python setup.py clean`, try to compile again and attach the full compile log here? Thanks!

**Comment by iotamudelta** [comment]
Sorry, getting back to this now. This looks like mkldnn is enabled where it shouldn't be. We have in the meantime just merged py3.6 support upstream and will hopefully switch the CI and our development infrastructure soon.

**Comment by iotamudelta** [comment]
Updated CI and everything else to python 3.6. Closing this issue.
