### ISSUE TITLE
Slow matrix multiply

### ISSUE THREAD

**Issue by Delaunay** [ROCmSoftwarePlatform/pytorch#398]
Matrix multiply through pytorch is slow. 
This causes reinforcement learning models / robotics models to run slow

```
GeForce RTX 2080 Ti : Ran everything in 24.958343505859375 s
Radeon VII: Ran everything in 147.59031534194946 s
```

```python
import torch
import torch.nn as nn
import time
import pandas as pd


class Flatten(nn.Module):
    def forward(self, x):
        return x.view(x.size(0), -1)


if __name__ == '__main__':

    device = torch.device('cuda')
    print(torch.cuda.get_device_name(device))

    count = 1000
    prev = None

    data = []

    all = time.time()
    # batch size
    for b in [2, 4, 8, 10, 16, 32, 64, 100, 128, 200, 256, 500, 512]:

        # Hidden Layer
        for h in [500, 512, 100, 1024, 2000, 2048]:

            # Output layer
            for o in [10, 500, 512, 100, 1024, 2000, 2048]:

                input = torch.rand(b, h).cuda()
                weight = torch.rand(h, o).cuda()

                for _ in range(0, 5):
                    out = input.mm(weight)
                torch.cuda.synchronize()

                s = time.time()
                for _ in range(0, count):
                    out = input.mm(weight)

                torch.cuda.synchronize()
                e = time.time()

                data.append([b, h, o, e - s])

    end = time.time()

    print(f'Ran everything in {end - all} s')

    df = pd.DataFrame(data)
    df.columns = ['b', 'h', 'o', 't']
    df.to_csv(f'{torch.cuda.get_device_name(device).replace(" ", "_").replace("/", "").replace("[", "")}.csv')

```

**Comment by iotamudelta** [comment]
@Delaunay can you tell whether this holds true across the board or just for a few outliers?

**Comment by Delaunay** [comment]
On average it is significantly slower. With the best configuration I had on the R VII ran 40%  slower than the 2080Ti. Given the results I had with convnets it should be at most 20% slower.  The worst configuration ran down to 95% slower. 

I think overall smaller configuration perform a lot worse and I could probably get close to 2080Ti results with huge matrices. 

The configurations that ran the worst are

b | h | o
-- | -- | --
10 | 2048 | 512
4 | 2048 | 500
10 | 2048 | 500
16 | 2048 | 512
2 | 2048 | 512
4 | 2048 | 512
8 | 2048 | 512

The configurations that run best are:

b | h | o
-- | -- | --
500 | 512 | 2048
500 | 512 | 2000
512 | 512 | 2048
512 | 512 | 2000
512 | 500 | 2048
500 | 500 | 2048
500 | 500 | 2000
512 | 500 | 2000

**Comment by Delaunay** [comment]
[GeForce_RTX_2080_Ti.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/3099282/GeForce_RTX_2080_Ti.txt)
[Vega_20.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/3099283/Vega_20.txt)

**Comment by iotamudelta** [comment]
Thanks so much! I took one of the worst configs (8/2048/512) and profiled it. Looks like the time is entirely spent inside of our rocBLAS library - I was expecting that. I'll talk to those folks to see what we can do about the performance there.

**Comment by Delaunay** [comment]
I reran the test using [deep_bench_nn.csv][1] from the tensile repo: R VII vs 2080Ti.
Posting the results

Average | -39.69%
-- | --
Median | -45.96%
Max  | +40.36%
Min | - 82.33%

```python
import torch
import time
import pandas as pd
import argparse
import itertools

input_size = [2, 4, 8, 10, 16, 32, 64, 100, 128, 200, 256, 500, 512]
hidden_size = [500, 512, 100, 1024, 2000, 2048]
output_size = [10, 500, 512, 100, 1024, 2000, 2048]

parser = argparse.ArgumentParser()
parser.add_argument('--input-size', type=int, nargs='*', default=input_size)
parser.add_argument('--hidden-size', type=int, nargs='*', default=hidden_size)
parser.add_argument('--output-size', type=int, nargs='*', default=output_size)
parser.add_argument('--repeat', type=int, default=1000)
parser.add_argument('--csv', type=str, default=None, help='tensile csv file'
    'https://github.com/ROCmSoftwarePlatform/Tensile/blob/develop/Tensile/Configs/deep_bench_nn.csv')

args = parser.parse_args()

input_size = args.input_size
hidden_size = args.hidden_size
output_size = args.output_size

configs = itertools.product(input_size, hidden_size, output_size)

if args.csv:
    csv = open(args.csv, 'r').read().split('\n')
    csv = map(lambda row: row.strip(), csv)
    csv = filter(lambda row: len(row) > 0, csv)
    configs = map(lambda row: map(lambda val: int(val), row.split(',')), csv)

device = torch.device('cuda')
print(torch.cuda.get_device_name(device))

prev = None

timings = []

all = time.time()
# batch size
for idx, (b, h, o) in enumerate(configs):
    input = torch.rand(b, h).cuda()
    weight = torch.rand(h, o).cuda()

    for _ in range(0, 5):
        out = input.mm(weight)
    torch.cuda.synchronize()

    s = time.time()
    for _ in range(0, args.repeat):
        out = input.mm(weight)

    torch.cuda.synchronize()
    e = time.time()

    t = e - s
    timings.append([b, h, o, t])
    print(f'{idx:6d}) b-{b:6d} h-{h:6d} o-{o:6d} {t:8.4f} s')

end = time.time()

print(f'Ran everything in {end - all} s')

df = pd.DataFrame(timings)
gpu = (torch.cuda.get_device_name(device)
       .replace(" ", "_")
       .replace("/", "")
       .replace("[", "")
       .replace(']', ""))
df.columns = ['b', 'h', 'o', 't']
df.to_csv(f'{gpu}.csv')

```
[tensile_bench.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/3103810/tensile_bench.txt)




[1]: https://github.com/ROCmSoftwarePlatform/Tensile/blob/develop/Tensile/Configs/deep_bench_nn.csv

**Comment by iotamudelta** [comment]
@Delaunay this should get better w/ the upcoming ROCm 2.5 release

**Comment by Delaunay** [comment]
Great news! Will it include RCCL 2 as well ? I think it is the only missing piece for distributed training in pytorch.

**Comment by iotamudelta** [comment]
You can already use distributed w/ GPU to host communication as of ROCm 2.4. I cannot comment on the RCCL roadmap here, sorry.

**Comment by Delaunay** [comment]
Np, so the TCP backend should work ?

**Comment by iotamudelta** [comment]
so far we've tested intranode multi-GPU, not internode.

**Comment by Delaunay** [comment]
I was able to test intra node multi-GPU (2).
I used gloo backend (TCP is deprecated) and had to do the all reduce on the CPU.
CPU is eating all the perf gain but at least it works.

One thing I noticed is that the compilation happens on all processes, but given the nature of python I am not sure if it can be avoided.

| GPU Count | Batch Size Per GPU | Img /sec |
|---|------|------|
| 1 | 32 | 131 |
| 1 | 16 | 92 |
| 2 | 32 | 135 |
| 2 | 16 |   92  |

**Comment by jithunnair-amd** [comment]
What number do you get for 64/128 batch size per GPU? Also, the img/sec remains the same for you regardless of 1 or 2 GPUs? Are you using the torch.DataParallel api?

**Comment by Delaunay** [comment]
the img /sec is computed like so (batch_size * number of GPU / time).
The code is here is you are [interested][1].

If I do

> ```python -m torch.distributed.launch --nproc_per_node=2 distri.py --backend gloo ~/datasets/mlperf/data/ImageNet/train --workers 4 --batch-size 16 --opt-level O0 --arch resnet101 --repeat 10 --number 10 --world-size 2```

vs 

> ```python -m torch.distributed.launch --nproc_per_node=1 distri.py --backend gloo ~/datasets/mlperf/data/ImageNet/train --workers 4 --batch-size 16 --opt-level O0 --arch resnet101 --repeat 10 --number 10 --world-size 1```

I get something like 90 img/sec vs 50 img/sec, which is the expected outcome.

but If I do `python micro.py --network resnet101 --batch-size 16 --iterations 10` using your [micro benchmark script][2] I get `Throughput [img/sec] : 118.33301211897968`. 

So the numbers are not 100% comparable but it seems gloo adds significant overheads
but it works



[1]: https://gist.github.com/Delaunay/dff3547102f6f90a855188ed69f701fd
[2]: https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Performance-analysis-of-PyTorch

**Comment by Delaunay** [comment]
Just re ran with rocm2.5 the matrix multiply benchmark.
On average improvements of +30%. Max improvement 321%, max regression -66%

Compared to the 2080Ti best configuration is 102% faster; the worst is 71% slower.

[tensile_bench.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/3274084/tensile_bench.txt)

**Comment by iotamudelta** [comment]
@Delaunay thanks for checking this - so overall it seems to be more solid now? I'll see that I can filter for the regressed sizes and have them be checked again.

**Comment by Delaunay** [comment]
It is hard to say. I think it improved greatly on a lot of problems where the matrices are big and square like
but some problems performing great got their performance greatly reduced like `b x 1 x o`.

I just tried taking the best of 2.5 with the best of 2.4 and from the 28% slower than 2080Ti on average it goes down to 16.27%.

![Screenshot_2019-06-11_07-58-43](https://user-images.githubusercontent.com/4311937/59274114-4c179700-8c1f-11e9-8826-6ac1a595edfb.png)

**Comment by iotamudelta** [comment]
@Delaunay can this be closed now? I see that you closed the rocBLAS issue.

**Comment by Delaunay** [comment]
Yeah, although, I have not actually checked that issue was resolved since I am no longer in possession of vega 20 GPUs. I would have liked to be able to though.
