### ISSUE TITLE
torchvision 0.3.0 is installing PyTorch 1.1.0 (CPU version) and removing ROCm/PyTorch

### ISSUE THREAD

**Issue by aurotripathy** [ROCmSoftwarePlatform/pytorch#411]
The latest torchvision, 0.3.0, is installing PyTorch 1.1.0 (CPU version) and removing ROCm/PyTorch
Looks like torchvision 0.3.0 _requires_ PyTorch 1.1.0. 
My workaround is to `pip install torchvision==0.2.0`
Is there any other install option?
Is this temporary?

**Comment by Delaunay** [comment]
I have the same issue.
I think another work around would be to use `pip install --no-deps torchvision`

```
$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
>>> import torch
>>> print(torch.__version__)
1.1.0a0+453c723
>>> exit()

$ pip install --upgrade torchvision
Collecting torchvision
  Downloading https://files.pythonhosted.org/packages/2e/45/0f2f3062c92d9cf1d5d7eabd3cae88cea9affbd2b17fb1c043627838cb0a/torchvision-0.3.0-cp36-cp36m-manylinux1_x86_64.whl (2.6MB)
    100% |████████████████████████████████| 2.6MB 7.1MB/s 
Collecting torch>=1.1.0 (from torchvision)
  Downloading https://files.pythonhosted.org/packages/69/60/f685fb2cfb3088736bafbc9bdbb455327bdc8906b606da9c9a81bae1c81e/torch-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (676.9MB)
    49% |████████████████                | 336.3MB 42kB/s eta 2:14:24^C
```

**Comment by pramenku** [comment]
Issue was due to torch commit https://github.com/pytorch/vision/commit/06b9b0fc53536c20dfca2de78c7df695b3c6c4d1

It has been fixed in latest vision commit  https://github.com/pytorch/vision/commit/c7a4ca99747bed619a5aa6a7a2814c26ce3622b6

We can build torchvision as below

git clone https://github.com/pytorch/vision --quiet
cd vision
pip install --user .

**Comment by aurotripathy** [comment]
Thanks all, closing.

**Comment by 401qingkong** [comment]
> Issue was due to torchvision commit [pytorch/vision@06b9b0f](https://github.com/pytorch/vision/commit/06b9b0fc53536c20dfca2de78c7df695b3c6c4d1)
> 
> It has been fixed in latest torchvision commit [pytorch/vision@c7a4ca9](https://github.com/pytorch/vision/commit/c7a4ca99747bed619a5aa6a7a2814c26ce3622b6) by revert of above commit.
> 
> ToT vision commit is working fine.
> 
> We can build torchvision as below
> 
> git clone https://github.com/pytorch/vision --quiet
> cd vision
> pip install --user .
> 
> pip install torchvision if not working ( may be due to absence of fix), we an use above build steps.
@aurotripathy @pramenku 
I can build torchvison successfully with your method. But when I run the vision examples in the path /vision/references/detection, the error occures as below:
`RuntimeError: Not compiled with GPU support (nms at /tmp/pip-req-build-8rqg7slj/torchvision/csrc/nms.h:20)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f0e3fc76037 in /public/home/facepp1/pytorch_2.6_ib_gloo/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: nms(at::Tensor const&, at::Tensor const&, float) + 0x3d0 (0x7f0e0e0710f0 in /public/home/facepp1/.local/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x1f03d (0x7f0e0e07e03d in /public/home/facepp1/.local/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x1bc4f (0x7f0e0e07ac4f in /public/home/facepp1/.local/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so)
frame #4: _PyCFunction_FastCallKeywords + 0x1bb (0x4fa9fb in /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3)
frame #5: /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3() [0x552d79]
frame #6: _PyEval_EvalFrameDefault + 0x2da (0x54b4ea in /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3)
frame #7: /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3() [0x553e6d]
frame #8: /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3() [0x552e5c]
frame #9: _PyEval_EvalFrameDefault + 0x2da (0x54b4ea in /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3)
frame #10: /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3() [0x553e6d]
frame #11: /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3() [0x552e5c]
frame #12: _PyEval_EvalFrameDefault + 0x2da (0x54b4ea in /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3)
frame #13: /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3() [0x54aa8e]
frame #14: /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3() [0x553f2b]
frame #15: /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3() [0x552e5c]
frame #16: _PyEval_EvalFrameDefault + 0x2da (0x54b4ea in /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3)
frame #17: /public/home/facepp1/pytorch_2.6_ib_gloo/bin/python3() [0x54a5b2]
`
How to compile torchvision with gpu support?
Thanks in advance

**Comment by streamhsa** [comment]
Try below to install torchvision and see if it works for you

pip install torchvision==0.2.2.post3

**Comment by pramenku** [comment]
Try below to install torchvision and see if it works for you

pip install torchvision==0.2.2.post3

**Comment by 401qingkong** [comment]
> pip install torchvision==0.2.2.post3

I can install torchvision0.2.2.post3 and  import it successfully, but the question is that the version don't include extension modules. Detection task needs to import torchvision._C，and the function imported by _C library comes from the csrc submodule in the vision project.  I notice the above gpu support error  comes from that I can't complie csrc code with gpu option(WITH_CUDA option in the code), I can't find a hip version for AMD gpus. So how to compile it with gpu?
could you give me some advice, thank you :)

**Comment by Delaunay** [comment]
The problem of compiling torchvision with ROCm is linked to this [issue][3]. 
Because torchvision uses [`CUDAExtension`][1] to compile the C sources and there is no equivalent for ROCm yet.

I think for [CUDAExtension ][2] to work with ROCm it would need first to hipify the source and then compile it using hcc instead of nvcc.


[1]: https://github.com/pytorch/vision/blob/fe234fc8cfae5fdbc9168994a0547c822631c3aa/setup.py#L102
[2]: https://github.com/pytorch/pytorch/blob/92c63d90e8efbd4711217cfd91c81d1a0e82319d/torch/utils/cpp_extension.py#L450
[3]: https://github.com/ROCmSoftwarePlatform/pytorch/issues/382

**Comment by 401qingkong** [comment]
> The problem of compiling torchvision with ROCm is linked to this [issue](https://github.com/ROCmSoftwarePlatform/pytorch/issues/382).
> Because torchvision uses [`CUDAExtension`](https://github.com/pytorch/vision/blob/fe234fc8cfae5fdbc9168994a0547c822631c3aa/setup.py#L102) to compile the C sources and there is no equivalent for ROCm yet.
> 
> I think for [CUDAExtension ](https://github.com/pytorch/pytorch/blob/92c63d90e8efbd4711217cfd91c81d1a0e82319d/torch/utils/cpp_extension.py#L450) to work with ROCm it would need first to hipify the source and then compile it using hcc instead of nvcc.

Yes, that's just what I want. It means that torch and torchvision project all have the C sources which need to be implemented with a hip version.(torchvision relies on torch C extention ), It seems like a huge amount of work. I want to know if you have a plan to implement a C extension hip version for ROCm.
