### ISSUE TITLE
Failed building source with ROCm 2.4 hip 

### ISSUE THREAD

**Issue by wormwang** [ROCmSoftwarePlatform/pytorch#415]
## To Reproduce

1. Ubuntu 18.04.2
2.gcc 7.4.0
3. hip ,hcc from ROCm 2.4

git clone https://github.com/ROCmSoftwarePlatform/pytorch.git
laster master

follow the guide of https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm

Error log:
make[2]: Entering directory '/home/motech/pytorch/build'
[ 89%] Linking CXX executable ../bin/reshape_op_gpu_test
cd /home/motech/pytorch/build/caffe2 && /usr/bin/cmake -E cmake_link_script CMakeFiles/reshape_op_gpu_test.dir/link.txt --verbose=1
[ 89%] Linking CXX executable ../bin/generate_proposals_op_util_nms_gpu_test
cd /home/motech/pytorch/build/caffe2 && /usr/bin/cmake -E cmake_link_script CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/link.txt --verbose=1
/usr/bin/c++    -fvisibility-inlines-hidden -fopenmp -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow -O3    -rdynamic CMakeFiles/reshape_op_gpu_test.dir/operators/hip/reshape_op_gpu_test.cc.o  -o ../bin/reshape_op_gpu_test -Wl,-rpath,/home/motech/pytorch/build/lib:/opt/rocm/rocrand/lib:/opt/rocm/hiprand/lib:/opt/rocm/hipsparse/lib:/opt/rocm/hip/lib:/opt/rocm/miopen/lib:/opt/rocm-2.3.0613/rocblas/lib:/opt/rocm-2.3.0613/rocfft/lib: ../lib/libgtest_main.a -Wl,--no-as-needed,/home/motech/pytorch/build/lib/libcaffe2.so -Wl,--as-needed -Wl,--no-as-needed,/home/motech/pytorch/build/lib/libcaffe2_hip.so -Wl,--as-needed ../lib/libcaffe2.so ../lib/libprotobuf.a ../lib/libc10_hip.so ../lib/libc10.so ../lib/libgloo_hip.a /opt/rocm/rocrand/lib/librocrand.so.1.8.2 /opt/rocm/hiprand/lib/libhiprand.so.1.8.2 /opt/rocm/hipsparse/lib/libhipsparse.so /opt/rocm/hip/lib/libhip_hcc.so /opt/rocm/miopen/lib/libMIOpen.so /opt/rocm-2.3.0613/rocblas/lib/librocblas.so.2.0.1.0 /opt/rocm-2.3.0613/rocfft/lib/librocfft.so.0.9.1.0 ../lib/libgloo.a -lpthread /usr/lib/aarch64-linux-gnu/libopenblas.so ../lib/libgtest.a -pthread 
/usr/bin/c++    -fvisibility-inlines-hidden -fopenmp -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow -O3    -rdynamic CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/operators/hip/generate_proposals_op_util_nms_gpu_test.cc.o  -o ../bin/generate_proposals_op_util_nms_gpu_test -Wl,-rpath,/home/motech/pytorch/build/lib:/opt/rocm/rocrand/lib:/opt/rocm/hiprand/lib:/opt/rocm/hipsparse/lib:/opt/rocm/hip/lib:/opt/rocm/miopen/lib:/opt/rocm-2.3.0613/rocblas/lib:/opt/rocm-2.3.0613/rocfft/lib: ../lib/libgtest_main.a -Wl,--no-as-needed,/home/motech/pytorch/build/lib/libcaffe2.so -Wl,--as-needed -Wl,--no-as-needed,/home/motech/pytorch/build/lib/libcaffe2_hip.so -Wl,--as-needed ../lib/libcaffe2.so ../lib/libprotobuf.a ../lib/libc10_hip.so ../lib/libc10.so ../lib/libgloo_hip.a /opt/rocm/rocrand/lib/librocrand.so.1.8.2 /opt/rocm/hiprand/lib/libhiprand.so.1.8.2 /opt/rocm/hipsparse/lib/libhipsparse.so /opt/rocm/hip/lib/libhip_hcc.so /opt/rocm/miopen/lib/libMIOpen.so /opt/rocm-2.3.0613/rocblas/lib/librocblas.so.2.0.1.0 /opt/rocm-2.3.0613/rocfft/lib/librocfft.so.0.9.1.0 ../lib/libgloo.a -lpthread /usr/lib/aarch64-linux-gnu/libopenblas.so ../lib/libgtest.a -pthread 
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_agent_get_info'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_load_agent_code_object'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_iterate_agent_symbols'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_isa_from_name'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_agent_global_variable_define'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_code_object_reader_destroy'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_system_major_extension_supported'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_system_get_major_extension_table'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_symbol_get_info'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_freeze'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_create_alt'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_code_object_reader_create_from_memory'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_amd_memory_lock'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_agent_iterate_isas'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/build.make:113: recipe for target 'bin/generate_proposals_op_util_nms_gpu_test' failed
make[2]: *** [bin/generate_proposals_op_util_nms_gpu_test] Error 1
make[2]: Leaving directory '/home/motech/pytorch/build'
CMakeFiles/Makefile2:3088: recipe for target 'caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_system_major_extension_supported'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_system_get_major_extension_table'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_isa_from_name'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_symbol_get_info'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_load_agent_code_object'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_iterate_agent_symbols'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_freeze'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_create_alt'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_executable_agent_global_variable_define'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_code_object_reader_destroy'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_code_object_reader_create_from_memory'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_amd_memory_lock'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_agent_iterate_isas'
/home/motech/pytorch/build/lib/libcaffe2_hip.so: error: undefined reference to 'hsa_agent_get_info'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/reshape_op_gpu_test.dir/build.make:113: recipe for target 'bin/reshape_op_gpu_test' failed
make[2]: *** [bin/reshape_op_gpu_test] Error 1
make[2]: Leaving directory '/home/motech/pytorch/build'
CMakeFiles/Makefile2:3043: recipe for target 'caffe2/CMakeFiles/reshape_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/reshape_op_gpu_test.dir/all] Error 2
make[1]: Leaving directory '/home/motech/pytorch/build'
Makefile:143: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 745, in <module>
    build_deps()
  File "setup.py", line 305, in build_deps
    build_dir='build')
  File "/home/motech/pytorch/tools/build_pytorch_libs.py", line 309, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '2', 'install']' returned non-zero exit status 2

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by iotamudelta** [comment]
Upstream CI hasn't had any failures to compile. Closing.
