### ISSUE TITLE
wiki documentation is points to wrong version

### ISSUE THREAD

**Issue by orena1** [ROCmSoftwarePlatform/pytorch#425]
## 📚 Documentation

step 2. state : docker pull rocm/pytorch:rocm**2.3_ubuntu16.04**

But in step 4:
sudo docker run -it -v $HOME:/data --privileged --rm --device=/dev/kfd --device=/dev/dri --group-add video rocm/pytorch:rocm**2.1**_ubuntu16.04
you ask to load the wrong docker.

Best,

**Comment by iotamudelta** [comment]
Thanks, fixed!

**Comment by orena1** [comment]
By the way @iotamudelta  is this docker only works with Ubuntu 16.04? if so I think it should state it.
THanks

**Comment by iotamudelta** [comment]
No, the docker should also work on other Linux operating systems as long as they run the kernel drivers supported by us. E.g., I ran these dockers on Ubuntu 19.04.

**Comment by orena1** [comment]
Thanks a lot, I tried but it required too much Ram (I think that more than the 16GB that is stated in the wiki).
