### ISSUE TITLE
Fastai/torchvision support

### ISSUE THREAD

**Issue by briansp2020** [ROCmSoftwarePlatform/pytorch#427]
## ❓ Questions and Help

I'm trying to get fastai working with ROCm/pytorch and am running into issues. I followed the direction in https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm except that I used rocm2.5_ubuntu16.04_py3.6 as the starting point. I was able to build pytorch and it seems to be installed correctly.

However, torchvision now seems to be built for cuda specifically. Does ROCm have plan to port torchvision to ROCm as well? Also, what is target date for releasing pytorch for ROCm for general public? 

I tried to use fastai before and there were some issues. https://github.com/ROCmSoftwarePlatform/pytorch/issues/258 I was hoping that things would work better now but I can't run it at all...

**Comment by briansp2020** [comment]
Output when trying to load fastai

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-283c0d40bede> in <module>
----> 1 from fastai.vision import *
      2 from fastai.metrics import error_rate

/usr/local/lib/python3.6/dist-packages/fastai/vision/__init__.py in <module>
      1 from .. import basics
      2 from ..basics import *
----> 3 from .learner import *
      4 from .image import *
      5 from .data import *

/usr/local/lib/python3.6/dist-packages/fastai/vision/learner.py in <module>
      4 from ..basic_data import *
      5 from .image import *
----> 6 from . import models
      7 from ..callback import *
      8 from ..layers import *

/usr/local/lib/python3.6/dist-packages/fastai/vision/models/__init__.py in <module>
      1 from .xresnet import *
----> 2 from torchvision.models import ResNet,resnet18,resnet34,resnet50,resnet101,resnet152
      3 from torchvision.models import SqueezeNet,squeezenet1_0,squeezenet1_1
      4 from torchvision.models import densenet121,densenet169,densenet201,densenet161
      5 from torchvision.models import vgg16_bn,vgg19_bn,alexnet

/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py in <module>
----> 1 from torchvision import models
      2 from torchvision import datasets
      3 from torchvision import ops
      4 from torchvision import transforms
      5 from torchvision import utils

/usr/local/lib/python3.6/dist-packages/torchvision/models/__init__.py in <module>
      9 from .shufflenetv2 import *
     10 from . import segmentation
---> 11 from . import detection

/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/__init__.py in <module>
----> 1 from .faster_rcnn import *
      2 from .mask_rcnn import *
      3 from .keypoint_rcnn import *

/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/faster_rcnn.py in <module>
      5 import torch.nn.functional as F
      6 
----> 7 from torchvision.ops import misc as misc_nn_ops
      8 from torchvision.ops import MultiScaleRoIAlign
      9 

/usr/local/lib/python3.6/dist-packages/torchvision/ops/__init__.py in <module>
----> 1 from .boxes import nms, box_iou
      2 from .roi_align import roi_align, RoIAlign
      3 from .roi_pool import roi_pool, RoIPool
      4 from .poolers import MultiScaleRoIAlign
      5 from .feature_pyramid_network import FeaturePyramidNetwork

/usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py in <module>
      1 import torch
----> 2 from torchvision import _C
      3 
      4 
      5 def nms(boxes, scores, iou_threshold):

ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

**Comment by iotamudelta** [comment]
torchvision works for us and on the PyTorch CI by cloning the repository and installing by `python setup.py install`. Can you try that?

Since the ROCm enablement is in upstream PyTorch and being tested as part of the CI, the general public can consume it.

**Comment by aurotripathy** [comment]
TorchVision 0.3.0 has an issue with ROCm (see #411 for workarounds). 

If you really don't need version 0.3.0, 

`pip install torchvision==0.2.2` or build it.
```
git clone https://github.com/pytorch/vision --quiet
cd vision
pip install --user . 
```

**Comment by briansp2020** [comment]
I was able to get fastai notebook to work by installing torchvision 0.2.2 but it does not seem to produce correct answer. Has anyone tried running https://github.com/fastai/course-v3/tree/master/nbs/dl1/lesson1-pets.ipynb?

**Comment by aurotripathy** [comment]
Did you do the following, i.e. install in no-deps mode.

`pip install --no-deps fastai`

**Comment by briansp2020** [comment]
@aurotripathy 
Forcing torchvision to v0.2.2 worked. So, I don't have install problem any more. However, fastai course notebook does not work properly (accuracy is very low after training). I hoping the main developers will take a look and see what is wrong. But at the moment, getting fastai library working does not seem like a priority for them...

**Comment by briansp2020** [comment]
Closing this since the issue is very old and pytorch/torchvision works with latest ROCm release
