### ISSUE TITLE
How to migrate compiled pytorch for direct use

### ISSUE THREAD

**Issue by 401qingkong** [ROCmSoftwarePlatform/pytorch#430]
When I compiled pytorch on one machine, how to migrate it to other machines for direct use.
Are there any files generated like wheel ? 
Thanks for your reply in advance!

**Comment by Delaunay** [comment]
You can use `python setup.py sdist bdist_wheel` to generate a wheel so other users could install your version without doing the compilation step.
`pip install torch-1.1.0a0+d8b9d32-cp36-cp36m-linux_x86_64.whl`

You won't be able to upload it to Pypi because it goes beyond the package size limit.

**Comment by 401qingkong** [comment]
@Delaunay Thanks for your reply. 
Is there any step to generate WHL files in the pytorch compilation process? I did not find it.

**Comment by Delaunay** [comment]
To my knowledge `python setup.py sdist bdist_wheel` is the only way to generate wheels.
It will re-compile and generate the wheels at the end
