### ISSUE TITLE
Multi-GPU support in ROCm2.5

### ISSUE THREAD

**Issue by 401qingkong** [ROCmSoftwarePlatform/pytorch#432]
I notice your note here[https://rocm-documentation.readthedocs.io/en/latest/Current_Release_Notes/Current-Release-Notes.html](url)
show multi-gpu functional support in rocm2.5. So which version of pytorch should i download and how to compile it. Should i add some args?

**Comment by Delaunay** [comment]
The multigpu support it compiled by default.
I always use the rocm pytorch master branch. it should be passing all the tests.

**Comment by 401qingkong** [comment]
@Delaunay I use the master branch of  rocm pytorch. and test it with your micro benchmark here [https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Performance-analysis-of-PyTorch](url)
But it outputs the warning like bleow when i used two gpus:
`[root@8e99eecbb895 amd_pytorch_case]# HIP_VISIBLE_DEVICES=0,1  python3 micro_benchmarking_pytorch.py --batch-size=16 --network=alexnet --dataparallel --device_ids=0,1 --fp16=1
INFO: running forward and backward for warmup.
/root/.local/lib/python3.6/site-packages/torch/cuda/nccl.py:24: UserWarning: PyTorch is not compiled with NCCL support
  warnings.warn('PyTorch is not compiled with NCCL support')
INFO: running the benchmark..
OK: finished running benchmark..
--------------------SUMMARY--------------------------
Microbenchmark for network : alexnet
Num devices: 2
Mini batch size [img] : 16
Time per mini-batch : 0.028506927490234375
Throughput [img/sec] : 561.267081676239`

Do i need recompile it with rccl? but i can't find the arg.  What's more, the same above command run with one gpu get the throughput about 1600.  So what’s the problem with multi-gpu support ?

**Comment by Delaunay** [comment]
You can ignore the warning. 
As far as I am aware RCCL support is disabled for now because the underlying library is not ready.

Regarding the micro benchmark script, the batch size you set is for the 2 GPUs.
So if you set `--batch-size=16` the batch size will be split between your two devices making it compute batches of 8. I would try a batch size of 32 so you can compare 2 GPU x 16 vs 1 GPU x 16.

**Comment by 401qingkong** [comment]
Can I run pytorch using horovod？
I compile pytorch with the following command：
`USE_DISTRIBUTED=1 USE_OPENMP=1 USE_MIOPEN=1 USE_ROCM=1 USE_LMDB=1 USE_OPENCV=1 python3 setup.py install --user`
then i install horovod and openmpi. And i run the example provided by hvd here [https://github.com/ROCmSoftwarePlatform/horovod/blob/hip/examples/pytorch_synthetic_benchmark.py](url) It outputs CUDA errors like below, 
`[qingkong@j01r1n18 examples]$ mpirun -np 2 python3 pytorch_synthetic_benchmark.py 
`
Traceback (most recent call last):
  File "pytorch_synthetic_benchmark.py", line 63, in <module>
    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
  File "/home/qingkong/python3_rocm2.1_distri/lib/python3.6/site-packages/horovod-0.16.2-py3.6-linux-x86_64.egg/horovod/torch/__init__.py", line 224, in broadcas
t_parameters    handle = broadcast_async_(p, root_rank, name)
  File "/home/qingkong/python3_rocm2.1_distri/lib/python3.6/site-packages/horovod-0.16.2-py3.6-linux-x86_64.egg/horovod/torch/mpi_ops.py", line 380, in broadcast
_async_    return _broadcast_async(tensor, tensor, root_rank, name)
  File "/home/qingkong/python3_rocm2.1_distri/lib/python3.6/site-packages/horovod-0.16.2-py3.6-linux-x86_64.egg/horovod/torch/mpi_ops.py", line 290, in _broadcas
t_async    tensor, output, root_rank, name.encode() if name is not None else _NULL)
RuntimeError: Internal error. Requested ReadyEvent with GPU device but not compiled with CUDA.
Traceback (most recent call last):
  File "pytorch_synthetic_benchmark.py", line 63, in <module>
    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
  File "/home/aiss/python3_rocm2.1_distri/lib/python3.6/site-packages/horovod-0.16.2-py3.6-linux-x86_64.egg/horovod/torch/__init__.py", line 224, in broadcas
t_parameters    handle = broadcast_async_(p, root_rank, name)
  File "/home/aiss/python3_rocm2.1_distri/lib/python3.6/site-packages/horovod-0.16.2-py3.6-linux-x86_64.egg/horovod/torch/mpi_ops.py", line 380, in broadcast
_async_    return _broadcast_async(tensor, tensor, root_rank, name)
  File "/home/aiss/python3_rocm2.1_distri/lib/python3.6/site-packages/horovod-0.16.2-py3.6-linux-x86_64.egg/horovod/torch/mpi_ops.py", line 290, in _broadcas
t_async    tensor, output, root_rank, name.encode() if name is not None else _NULL)
RuntimeError: Internal error. Requested ReadyEvent with GPU device but not compiled with CUDA.
What's wrong?

**Comment by Delaunay** [comment]
Distributed usually means multi node & multi GPU. 
At the moment only multi GPU is supported, distributed will come later with RCCL.

Although I know the gloo distributed backend with reduce on the CPU works.
I never tried horovod so I can only speculate. 
The error looks like it was not compiled with the required libraries to handle CUDA events.

**Comment by 401qingkong** [comment]
How can i use gloo distributed backend,  What do I need to configure in pytorch, and are there any examples?
By the way,  Does Multi-GPU only support in the latest ROCm2.5 version, or it  is  implemented in the  latest pytorch version, and can runs on any ROCm version?

**Comment by 401qingkong** [comment]
when i run multi-gpu test, the following mistakes often occur. And i try to increase the number of MAX_JOBS when compiling pytorch, but it doesn't seem to work. What's the matter? 
`[root@eb50a312fd8a amd_pytorch_case]# HIP_VISIBLE_DEVICES=0,1 python3.6 micro_benchmarking_pytorch.py --batch-size=64 --network=resnet50 --dataparallel --dev
ice_ids=0,1`
INFO: running forward and backward for warmup.
Memory access fault by GPU node-2 (Agent handle: 0x111e8f0) on address 0x1000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)

**Comment by Delaunay** [comment]
Multi GPU should be in pytorch master but I always use the rocm repo to compile for AMD.

Which GPU are you using ? There are some known issues for gfx803 (RX5XX)

* `MAX_JOBS` is only the number of parallel processes used to compile pytorch.

```
import torch.distributed as dist

# Use address of one of the machines
dist.init_process_group('gloo', init_method='tcp://10.1.1.20:23456', rank=args.rank, world_size=4)
```

**Comment by 401qingkong** [comment]
I used gfx906 in rocm2.1. And l also test multi-gpu  performance in Rocm2.5 , there are no problems with ROCm2.5.  So how can  I run successfully in 2.1.
Does your pytorch already support multi-node distributed computing with gloo backend?

**Comment by iotamudelta** [comment]
To comment on some of the questions in this thread:
* we do not support running on older platforms than the current ROCm release (2.5 at the moment)
* distributed parallel is in the process of being upstreamed. There is an open PR for gloo to add RCCL support, subsequently the submodule in PyTorch need to be updated, followed finally with our RCCL enablement in PyTorch landing
* in the meantime, only data parallel is supported in PyTorch

**Comment by jithunnair-amd** [comment]
As mentioned in the previous comment, a lot of changes related to RCCL/DistributedDataParallel/mGPU enablement were made over the past few months and have also been upstreamed and tested. Closing this issue for now, please reopen it if you still notice any issues.
