### ISSUE TITLE
[Caffe2] Cudnn operator update

### ISSUE THREAD

**Issue by petrex** [ROCmSoftwarePlatform/pytorch#44]
The goal is to review cudnn implementation of ops and implement miopen version if applicable

- affine_channel
- sigmoid/tanh
- transpose
- dropout
- **depthwise_3x3_conv**

**Comment by ashishfarmer** [comment]
Update:

- Affine channel -> typo. There is no Affine channel CUDNN or MIOpen operation, and C2 uses CUDA/HIP for that operation
- Sigmoid -> Done
- Tanh -> Done
- Dropout -> Not supported in MIOpen

**Comment by ashishfarmer** [comment]
Transpose conv -> done
