### ISSUE TITLE
"torch.version.cuda" is silent

### ISSUE THREAD

**Issue by aurotripathy** [ROCmSoftwarePlatform/pytorch#513]
## To Reproduce

Launch a published container:

`sudo docker run -it --rm --network=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $HOME/dockerx:/dockerx <dockername>`

In the container, type:

```
root@h2-hq-01:/# python
Python 3.6.9 (default, Jul  3 2019, 15:36:16)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.version.cuda
```

Is 'cuda' a proxy for any GPU driver layer? 
If so, is it appropriate to present the ROCm version?

Thanks.

**Comment by iotamudelta** [comment]
`cuda` throughout PyTorch means ROCm if on ROCm. @t-vi and I were talking about switching this to the ROCm version.

**Comment by iotamudelta** [comment]
we now have `torch.version.hip` populated thanks to @t-vi.

**Comment by aurotripathy** [comment]
Thank you. Confirming that it works in ROCm 3.0. 
```
(mlperf) root@penguin02:~/test/collect_rocm_env# python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.version.hip
'3.0.19493-36529b1'

```
