### ISSUE TITLE
Pytorch Install Instructions

### ISSUE THREAD

**Issue by Delaunay** [ROCmSoftwarePlatform/pytorch#515]
## 📚 Documentation

Pytorch build [instructions][1] are a bit outdated

[1]: https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm#option-4-install-directly-on-host

1. New rocm dependency roctracer (ROCTX) 

> rock-dkms rocm-dev rocm-libs miopen-hip hipsparse rocthrust hipcub rccl **roctracer-dev**

4. New sed command for rccl

> sed -i 's/find_dependency(hip)/find_dependency(HIP)/g' /opt/rocm/rccl/lib/cmake/rccl/rccl-config.cmake

I also had to add RCCL linking path `export LIBRARY_PATH="/opt/rocm/rccl/lib/"`.
Although CMake did say it found it and `ld -lrccl` was not able to find it either.

**Comment by ghostplant** [comment]
Is there a prebuilt version for pytorch >= 1.0?

**Comment by iotamudelta** [comment]
@ghostplant yes, see `https://hub.docker.com/r/rocm/pytorch/tags`

**Comment by ghostplant** [comment]
@iotamudelta I tried that but torch library are not included in the python runtime:
```sh
$ docker run -it --rm --network=host --privileged rocm/pytorch:rocm2.9_ubuntu18.04_py3.6 python3 -c 'import torch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
```

**Comment by jithunnair-amd** [comment]
Please try the ones with '_torch' in their tag, and specify 'python3.6' instead of 'python3' (sometimes the dockers have python3.5 linked to python). HTH

**Comment by ghostplant** [comment]
@jithunnair-amd Thanks, seems that for rocm-2.9, only py2.7 contains the pytorch but py3.6 doesn't.

**Comment by jithunnair-amd** [comment]
Seems okay on my end:
```
user@machine:~$ rundocker --name DELETE_ME rocm/pytorch:rocm2.9_ubuntu16.04_py3.6_pytorch
root@d3811f1dcda9:/# python3 --version
Python 3.5.2
root@d3811f1dcda9:/# python3.6
Python 3.6.9 (default, Jul  3 2019, 15:36:16)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__file__
'/root/.local/lib/python3.6/site-packages/torch/__init__.py'
```

**Comment by Delaunay** [comment]
Your both correct, ubuntu18.04 does not have pytorch but ubuntu16.04 does

```
sudo docker run -it rocm/pytorch:rocm2.9_ubuntu18.04_py3.6 bash
root@0070379bf58b:/# python3.6 -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
```

```
sudo docker run -it rocm/pytorch:rocm2.9_ubuntu16.04_py3.6_pytorch bash
root@58934992cf7d:/# python3.6 -c "import torch"
root@58934992cf7d:/# 
```

**Comment by jithunnair-amd** [comment]
@Delaunay Wiki has been updated for the sed command and dependency update. However, you shouldn't need to modify your LIBRARY_PATH for rccl, as the cmake build should find the rccl library and use the absolute path in the build. Can you please try again and let us know if you still observe the issue with finding rccl library? You can use VERBOSE=1 during the build and capture the log file to observe which build command uses '-lrccl', if any.

**Comment by Delaunay** [comment]
I will close the issue, I do not have access to the machine with AMD GPUs anymore so I wont be able to test again for the RCCL linking issue.
I assume it was probably just an issue with my setup
