### ISSUE TITLE
Aten missing files for caffe2_hip

### ISSUE THREAD

**Issue by geekonedge** [ROCmSoftwarePlatform/pytorch#54]
## Issue description

Aten appears to me missing files for caffe2_hip and prevents the installation of torch

In file included from /home/user/dev/pytorch/aten/src/THC/THCTensorIndex.cu:12:
/home/user/dev/pytorch/aten/src/THC/THCAtomics.cuh:145:35: error: static declaration of 'atomicAdd' follows non-static declaration
  static inline  __device__  void atomicAdd(double *address, double val) { }
                                  ^
/opt/rocm/hip/include/hip/hcc_detail/hip_atomic.h:73:8: note: previous definition is here
double atomicAdd(double* address, double val)
       ^
1 error generated.
[100%] Linking HIP shared library ../lib/libcaffe2_hip.so
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THC/caffe2_hip_generated_THCTensorIndex.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THC/caffe2_hip_generated_THCTensorScatterGather.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_FeatureLPPooling.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_IndexLinear.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_SpatialAdaptiveAveragePooling.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_SpatialAdaptiveMaxPooling.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_SpatialClassNLLCriterion.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_SpatialFractionalMaxPooling.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_SpatialGridSamplerBilinear.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_SpatialReflectionPadding.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_SpatialReplicationPadding.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_SpatialSubSampling.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_SpatialUpSamplingBilinear.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_SpatialUpSamplingNearest.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_TemporalMaxPooling.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_TemporalReflectionPadding.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_TemporalReplicationPadding.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_TemporalUpSamplingLinear.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_TemporalUpSamplingNearest.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_VolumetricAdaptiveAveragePooling.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_VolumetricAdaptiveMaxPooling.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_VolumetricAveragePooling.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_VolumetricDilatedMaxPooling.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_VolumetricFractionalMaxPooling.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_VolumetricGridSamplerBilinear.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_VolumetricReplicationPadding.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_VolumetricUpSamplingNearest.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/THCUNN/caffe2_hip_generated_VolumetricUpSamplingTrilinear.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/ATen/native/cuda/caffe2_hip_generated_Activation.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/ATen/native/cuda/caffe2_hip_generated_Distributions.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/ATen/native/cuda/caffe2_hip_generated_EmbeddingBag.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/ATen/native/cuda/caffe2_hip_generated_Gesv.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/ATen/native/cuda/caffe2_hip_generated_SummaryOps.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/ATen/native/cuda/caffe2_hip_generated_TensorCompare.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/ATen/native/sparse/cuda/caffe2_hip_generated_SparseCUDATensor.cu.o'
clang-7.0: error: no such file or directory: 'CMakeFiles/caffe2_hip.dir/__/aten/src/ATen/native/sparse/cuda/caffe2_hip_generated_SparseCUDATensorMath.cu.o'
[100%] Built target caffe2_hip
Install the project...

CMake Error at caffe2/cmake_install.cmake:69 (file):
  file INSTALL cannot find
  "/home/user/dev/pytorch/build/lib/libcaffe2_hip.so".
Call Stack (most recent call first):
  cmake_install.cmake:86 (include)

## System Info

Ubuntu 16.04
Kernel 4.13.0-45-generic

**Comment by Jorghi12** [comment]
You appear to be using HIP from the master branch, which comes with hip atomics definitions. Applying this [PR here](https://github.com/ROCmSoftwarePlatform/pytorch/pull/7) should solve your issue.

**Comment by geekonedge** [comment]
@Jorghi12 thanks for the note. I anticipated that might be the issue. Thanks again for the help!

**Comment by geekonedge** [comment]
I can confirm this is fixed by the PR referenced above
