### ISSUE TITLE
Make rocm docker images consistent with pytorch/pytorch:latest images

### ISSUE THREAD

**Issue by Delaunay** [ROCmSoftwarePlatform/pytorch#540]
## 🚀 Feature

Make rocm docker images consistent with pytorch/pytorch:latest images so they can be used
as drop in replacement.

## Motivation

Currently rocm docker images are a bit different from the official pytorch images.
Which requires people to write custom logic for ROCm

```
# default python is 3.5 but pytorch is installed on 3.6   
ln -f /usr/bin/python3.6 /usr/bin/python3
ln -f /usr/bin/python3.6 /usr/bin/python

# pip is an old version and does not work well
# It is also weirdly installed
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
```

**Comment by jithunnair-amd** [comment]
Can you please elaborate on the "pip does not work well, and is weirdly installed" comment? I do see that pip is installed in `/usr/local/lib/python3.6/dist-packages/` in the ROCm dockers, and I agree that it's an older version, but I would like to understand why it does not work well or is considered weirdly installed?

**Comment by Delaunay** [comment]
I had issue installing packages inside the container.
I would get random segmentation fault in the container while installing packages.
The segmentation faults were not tied to a particular package, they seemed to happened randomly when running pip. I had to rerun pip multiple times to get all the dependencies installed.

I use the same makefile for different containers to run the tests on different platform like so: https://gist.github.com/Delaunay/f0c7ef631646efba9136b1853ecc948e
So the make file should be fine, I only had that issue for ROCm containers.

```
$ sudo docker run -it -v /mnt/zshare/cache:/cache:rw -v /mnt/zshare/cache/docker:/workspace:rw --device=/dev/kfd --device=/dev/dri  rocm/pytorch:rocm2.9_ubuntu16.04_py3.6_pytorch bash
$ pip install --upgrade pip
$ pip install wheel
$ pip install torchvision==0.2.2
$ cd workspace/runner-7H6ybEyk-project-15606485-concurrent-1/c33bcaa1fd2c77edfc3893b41966cea8/Delaunay/olympus
$ make travis-install
Successfully built orion track
Installing collected packages: pymongo, smmap2, gitdb2, gitpython, filelock, AppDirs, orion, cryptography, dataclasses, track, atari-py
Makefile:6: recipe for target 'travis-install' failed
make: *** [travis-install] Segmentation fault (core dumped)
$ make travis-install
[...]
Successfully built orion track
Installing collected packages: pymongo, smmap2, gitdb2, gitpython, filelock, AppDirs, orion, cryptography, dataclasses, track, atari-py
Makefile:6: recipe for target 'travis-install' failed
make: *** [travis-install] Segmentation fault (core dumped)
$ make travis-install
Collecting sphinx-serve
  Downloading https://files.pythonhosted.org/packages/6b/6c/4e92f63609a489898d6b257aa721a844416468a3121febef9ae8a0be531e/sphinx-serve-1.0.1.tar.gz
    ERROR: Command errored out with exit status -11:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-igcjra56/sphinx-serve/setup.py'"'"'; __file__='"'"'/tmp/pip-install-igcjra56/sphinx-serve/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-igcjra56/sphinx-serve/pip-egg-info
         cwd: /tmp/pip-install-igcjra56/sphinx-serve/
    Complete output (0 lines):
    ----------------------------------------
ERROR: Command errored out with exit status -11: python setup.py egg_info Check the logs for full command output.
Makefile:6: recipe for target 'travis-install' failed
make: *** [travis-install] Error 1
...
$ make travis-install
...
Installing collected packages: coverage, pytest-cov, codecov
Successfully installed codecov-2.0.15 coverage-5.0.1 pytest-cov-2.8.1
```

**Comment by jithunnair-amd** [comment]
I do not know why you see the seg faults. However, the pip install and python3 pointing to python3.5, while being out-of-date/annoying, is what we get when building ROCm pytorch dockers using the pytorch scripts.

**Comment by jithunnair-amd** [comment]
@Delaunay Which gfx version were these segfaults on btw? gfx803/gfx900?

**Comment by Delaunay** [comment]
gfx803 in that case

**Comment by iotamudelta** [comment]
`gfx803` unfortunately is a bit rough around the edges as upstream testing happens on `gfx900` and `gfx906`. We enable it as a community service / best effort.
