### ISSUE TITLE
[PyTorch] Complete rocRAND Integration.

### ISSUE THREAD

**Issue by Jorghi12** [ROCmSoftwarePlatform/pytorch#55]
Currently, rocRAND is only partially integrated with PyTorch. However, it still remains nonfunctional at the time being. This PR is for ensuring that the rocRAND integration successfully achieves 100% of tests passing. This will require coordination with rocRAND  lead developers @jszuppe & @ex-rzr.

**Comment by iotamudelta** [comment]
Done.
