### ISSUE TITLE
Pytorch 1.3.1 on ROCm 3.0, compatibility

### ISSUE THREAD

**Issue by dodatko** [ROCmSoftwarePlatform/pytorch#560]
Few questions:

1. In original pytorch/pytorch repository 1.3.1 release tagged as v1.3.1, what related version(tag, commit) I can checkout in ROCmSoftwarePlatform/pytorch repository to get maximum compatibility?
2. On host system I have installed ROCm 3.0, should it work fully correct with pytorch 1.3.1 or I need to downgrade installed 3.0 to 2.x?
3. Is it normal to have ROCm 3.0 on host system and ROCm 2.10 in docker with Pytorch?

Now I have some problems with FastAI 1.60 and trying to fix them.

Thanks!

**Comment by iotamudelta** [comment]
1/2) PyTorch upstream will not work with ROCm 3.0 unless you integrate pytorch@3a7ecd3 patch.
3) Having a ROCm 3.0 host system and a ROCm 2.10 docker should work.

**Comment by dodatko** [comment]
@iotamudelta thanks!
