### ISSUE TITLE
Issue templates should be updated

### ISSUE THREAD

**Issue by lemairecarl** [ROCmSoftwarePlatform/pytorch#564]
The github issue templates of this repo are identical to those of the original pytorch repo. It's somewhat confusing, as it appears as if we are filing an issue for pytorch.

https://github.com/ROCmSoftwarePlatform/pytorch/tree/master/.github/ISSUE_TEMPLATE

**Comment by iotamudelta** [comment]
It's a straight clone - we also share the CI with upstream and track master very closely. Hence why we do not deviate from upstream even in issue templates, the information there is valuable to us as well.

**Comment by lemairecarl** [comment]
I see.

For example, I would have suggested to remove https://github.com/ROCmSoftwarePlatform/pytorch/blob/master/.github/ISSUE_TEMPLATE/documentation.md, since it does not make sense to receive issues about pytorch's docs here.

But I understand that you want to keep the tracking as straightforward as possible. Are you working with AMD? Do you know if AMD pays people to work on the project?

Thanks.

**Comment by Delaunay** [comment]
ROCm (Radeon Open Compute) is AMD stack and this is AMD official fork of pytorch

**Comment by iotamudelta** [comment]
Note that there are plenty of commits upstream from people with `@amd.com` email addresses (including myself), if that answers the question concerning AMD's commitment/involvement. :-)

**Comment by lemairecarl** [comment]
thanks
