### ISSUE TITLE
[PyTorch] Re-enable ATen ROCm tests.

### ISSUE THREAD

**Issue by Jorghi12** [ROCmSoftwarePlatform/pytorch#57]
PyTorch ROCm for a while had the ATen ROCm tests disabled https://github.com/ROCmSoftwarePlatform/pytorch/blob/master/caffe2/CMakeLists.txt#L341

Basically, re-enable them and handle any HCC related issues that come up in the process of doing so.

**Comment by iotamudelta** [comment]
Can be closed - is outdated.
