### ISSUE TITLE
[PyTorch] Docker Image and Documentation

### ISSUE THREAD

**Issue by Jorghi12** [ROCmSoftwarePlatform/pytorch#59]
Create documentation for the open source community on how to start working with the ROCm PyTorch Docker Image. Provide a clear summary on what's supported at the moment and what's on the agenda.

**Comment by iotamudelta** [comment]
We have [this wiki entry](https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm) now. It is also used by CQE.

Missing: what's supported.

**Comment by iotamudelta** [comment]
Exists.
