### ISSUE TITLE
ROCM 3.0&3.1: Memory leak in torch.nn.BCELoss

### ISSUE THREAD

**Issue by ant1s** [ROCmSoftwarePlatform/pytorch#594]
## Issue description
Hello.
My gpu is radeon vii and I use pytorch build with master branch 1.5.0a0+914610d and rocm 3.0. I found memory leaking in torch.nn.BCELoss, which make me can not do any long time trainning. 
I update rocm to 3.1 and the there still is memory leaking. I also tried my test script in cuda enviroment and no memory leak, so I guess there is something wrong with pytorch and rocm.

## Code example
here is my test script

```
device = torch.device('cuda:0')
#device = torch.device('cpu') # this will not leak memory
batch_size = 128
criterion = torch.nn.BCELoss()
label = torch.tensor(np.random.random((batch_size, 1))).to(device).float()
output = torch.tensor(np.random.random((batch_size, 1))).to(device).float()
for i in range(5000):
    train_loss = criterion(output, label)
    if i % 100 == 0:
        virtual_memory = psutil.virtual_memory()
        used_memory = virtual_memory.used >> 20
        print('iter {}, current memory {}MB'.format(i, used_memory))
    time.sleep(0.001)
```

the output is:
iter 0, current memory 13464MB
iter 100, current memory 13464MB
iter 200, current memory 13465MB
iter 300, current memory 13466MB
iter 400, current memory 13467MB
iter 500, current memory 13469MB
iter 600, current memory 13471MB
iter 700, current memory 13473MB
iter 800, current memory 13474MB
iter 900, current memory 13475MB
iter 1000, current memory 13477MB
iter 1100, current memory 13479MB
iter 1200, current memory 13480MB
iter 1300, current memory 13482MB
iter 1400, current memory 13482MB
iter 1500, current memory 13483MB
iter 1600, current memory 13485MB
iter 1700, current memory 13486MB
iter 1800, current memory 13486MB
iter 1900, current memory 13486MB
iter 2000, current memory 13489MB
iter 2100, current memory 13491MB
iter 2200, current memory 13492MB
iter 2300, current memory 13493MB
iter 2400, current memory 13493MB
iter 2500, current memory 13494MB
iter 2600, current memory 13495MB
iter 2700, current memory 13497MB
iter 2800, current memory 13499MB
iter 2900, current memory 13500MB
iter 3000, current memory 13502MB
iter 3100, current memory 13509MB
iter 3200, current memory 13505MB
iter 3300, current memory 13507MB
iter 3400, current memory 13508MB
iter 3500, current memory 13509MB
iter 3600, current memory 13510MB
iter 3700, current memory 13512MB
iter 3800, current memory 13513MB
iter 3900, current memory 13515MB
iter 4000, current memory 13516MB
iter 4100, current memory 13520MB
iter 4200, current memory 13520MB
iter 4300, current memory 13520MB
iter 4400, current memory 13520MB
iter 4500, current memory 13520MB
iter 4600, current memory 13520MB
iter 4700, current memory 13520MB
iter 4800, current memory 13520MB
iter 4900, current memory 13521MB

## System Info
Collecting environment information...
PyTorch version: 1.5.0a0+914610d
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] pytorchcv==0.0.57
[pip3] torch==1.5.0a0+914610d
[pip3] torchvision==0.6.0a0+0156d58
[conda] Could not collect

any way could avoid it will help me a lot, thanks!

**Comment by Delaunay** [comment]
Do you run out of memory at some point ?
CPU memory or GPU memory ?

I had memory issue as well with pytorch when using small GPU tensors.
Basically, the python GC not being aware of GPU memory & pytorch caching GPU memory means you can experience very interesting behaviors.

ROCm use slightly less memory than CUDA that means you could be hitting a weird edge case where small objects are not reclaimed soon enough and pytorch keeps allocating new GPU tensor.
In my case, I solved my issue by forcing python to GC after each backward pass using the code below.

        import gc
        gc.collect(2)

**Comment by ant1s** [comment]
> Do you run out of memory at some point ?
> CPU memory or GPU memory ?
> 
> I had memory issue as well with pytorch when using small GPU tensors.
> Basically, the python GC not being aware of GPU memory & pytorch caching GPU memory means you can experience very interesting behaviors.
> 
> ROCm use slightly less memory than CUDA that means you could be hitting a weird edge case where small objects are not reclaimed soon enough and pytorch keeps allocating new GPU tensor.
> In my case, I solved my issue by forcing python to GC after each backward pass using the code below.
> 
> ```
>     import gc
>     gc.collect(2)
> ```

yes ,my trainning program will stuck after all memory(include swap memory) exhusted, but when I test with the script, there seems an upper limit. I will do more work on it

here is my trainning loop:

```
num_epochs = 100

optimizer = optim.SGD(model.parameters(), lr=1e-6)
step_size = len(train_set) // batch_size * num_epochs // 8
scheduler = optim.lr_scheduler.CyclicLR(optimizer, base_lr=1e-6, max_lr=1e-2, step_size_up=step_size, step_size_down=None, mode='triangular', gamma=1.0, scale_fn=None, scale_mode='cycle', cycle_momentum=True, base_momentum=0.8, max_momentum=0.9, last_epoch=-1)

train_criterion = nn.BCELoss()

total_time = 0
best_loss = np.inf

for i in range(num_epochs):
    running_loss = 0.0
    running_corrects = 0
    since = time.time()
    for data, labels in tqdm(train_data_loader):
        data = data.cuda()
        label = labels.cuda().float()
        
        optimizer.zero_grad()
        output = model(data)
        output_sigmoid = torch.sigmoid(output)
        preds = torch.round(output_sigmoid).flatten()
        train_loss = train_criterion(output_sigmoid, label)
        train_loss.backward()
        optimizer.step()
        scheduler.step()
        
        running_loss += train_loss.item() * data.size(0)
        running_corrects += torch.sum(preds == torch.round(label.data)).item()
    
    epoch_loss = running_loss / len(train_set)
    train_acc = running_corrects / len(train_set)
```

I test memory leak by comment code.I can observe memory growth only when `train_criterion(output_sigmoid, label)` is not commented

**Comment by ant1s** [comment]
I found that the torch.nn.BCELoss is not the real reason, I will close this issue.
Sorry for the wrong report!
