### ISSUE TITLE
Warning: PyTorch no longer supports this GPU because it is too old.

### ISSUE THREAD

**Issue by Laser-Cat** [ROCmSoftwarePlatform/pytorch#627]
## To Reproduce

1.Open a python interpreter
2. import torch;tensor([9], device='cuda:0');

```
/home/lasercat/.local/lib/python3.6/site-packages/torch/cuda/__init__.py:87: UserWarning: 
    Found GPU0 Ellesmere [Radeon RX 470/480/570/570X/580/580X] which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
tensor([9], device='cuda:0')

```
## Expected behavior
The warning should not appear, or shown in a understandable manner.
For example(I dunno if gfx803 is really too old or just they have an outdated hack to decive pytorch):
```
/home/lasercat/.local/lib/python3.6/site-packages/torch/cuda/__init__.py:87: UserWarning: 
    Found GPU0 Ellesmere [Radeon RX 470/480/570/570X/580/580X] which is of gfx803.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is gfx900.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
tensor([9], device='cuda:0')

```

## Environment

 - PyTorch Version (e.g., 1.0): '1.6.0a0+93432cf'
 - OS (e.g., Linux): Ubuntu 18.04.4
 - How you installed PyTorch (`conda`, `pip`, source):
source
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version:None
 - Rocm/Miopen version: 3.3/2.3
- GPU models and configuration: Rx590(12nm), gfx803
 - Any other relevant information:

**Comment by iotamudelta** [comment]
Thanks, this warning unfortunately got introduced upstream for the CUDA path but does not reflect the realities for the ROCm path. It is purely cosmetic and there is a PR upstream to remove the warning for ROCm.
