### ISSUE TITLE
UserWarning: cuDNN/MIOpen library not found. Check your LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by harish2704** [ROCmSoftwarePlatform/pytorch#631]
## Issue description
When running  ROCm Pytorch, I am getting the following warning
`UserWarning: cuDNN/MIOpen library not found. Check your LD_LIBRARY_PATH`
which is coming from `torch/backends/cudnn/__init__.py:81`

I do not have cuDNN insatllation, but I do have  MIOpen installation. ( and it was detected correctly during pytorch build process )

My question is whether is warning is an expected behavior or not.
If ROCm Pytorch actually need  cuDNN, then warning message should clearly say that.
the term "cuDNN/MIOpen"  is confusing

## System Info
```
Collecting environment information...
PyTorch version: 1.6.0a0+a4d4c78
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Fedora 31 (Workstation Edition)
GCC version: (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
CMake version: version 3.17.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.0
[pip3] torch==1.6.0a0+a4d4c78
[pip3] torchvision==0.5.0
[conda] Could not collect

```

ROCm Pytorch version: a4d4c785e1c6f9eff746202e3ad50bcb71a0e649

**Comment by iotamudelta** [comment]
This is a warning that unfortunately does not reflect reality. @jithunnair-amd to explain

**Comment by harish2704** [comment]
@iotamudelta : Yes. I fixed this and found that, it doesn't add anything to performance. 
Any way, I made small fix for that

**Comment by jithunnair-amd** [comment]
This issue should be fixed by PR https://github.com/pytorch/pytorch/pull/33837
