### ISSUE TITLE
[PyTorch] Update sccache to support HCC

### ISSUE THREAD

**Issue by Jorghi12** [ROCmSoftwarePlatform/pytorch#64]
In order to improve build times, I've extended sccache to support HCC: https://github.com/Jorghi12/sccache. Once a full enumeration of the HCC command line arguments are obtained, I'll send a more robust solution upstream into Mozzila's sccache branch.

**Comment by Jorghi12** [comment]
**HIPCC update:**
https://github.com/ROCm-Developer-Tools/HIP/pull/586

**Comment by iotamudelta** [comment]
CI uses `sccache` successfully.
