### ISSUE TITLE
Evaluate  clang5 v.s. clang 3.8 for pytorch

### ISSUE THREAD

**Issue by petrex** [ROCmSoftwarePlatform/pytorch#66]

**Comment by petrex** [comment]
This is for pytorch/caffe2 on rocm 1.8.2; seeing constraint for production.

**Comment by petrex** [comment]
The root cause:

https://github.com/ROCm-Developer-Tools/HIP/blob/73ef5312086ce039f7d7c787f3c2866ec397a81e/include/hip/hcc_detail/hip_fp16.h#L32

**Comment by ashishfarmer** [comment]
The issue will be fixed with hip-clang. We will continue using clang-3.8 for building until then
