### ISSUE TITLE
PyTorch cannot manipulate multiple GPUs 

### ISSUE THREAD

**Issue by kazulittlefox** [ROCmSoftwarePlatform/pytorch#669]
## 🐛 Bug

PyTorch installed on Anaconda environment cannot manipulate multiple GPUs properly, and it may cause further crashes.

## To Reproduce

1.Install user-built PyTorch wheel package for GFX906 via pip(further information: https://github.com/aieater/rocm_pytorch_informations#source-build-for-developers)
2.install huggingface/transformers via pip
3.run huggingface/transformers example(huggingface/transformers/examples/summarization/bart/run_train.sh) and caused by the error below:

```
Resume from checkpoint: ../../../../ckpt/hybrid/hybrid_epoch1.ckpt
Initialize trainer...
[W Module.cpp:455] Warning: Disabling benchmark mode for MIOpen is NOT supported. Overriding value to True (function operator())
Traceback (most recent call last):
  File "finetune.py", line 179, in <module>
    main(args)
  File "finetune.py", line 160, in main
    trainer = generic_train(model, args)
  File "/root/lds/transformers/examples/lightning_base.py", line 287, in generic_train
    trainer = pl.Trainer(**train_params)
  File "/root/anaconda3/envs/transformers/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 464, in __init__
    self.data_parallel_device_ids = parse_gpu_ids(self.gpus)
  File "/root/anaconda3/envs/transformers/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 730, in parse_gpu_ids       
    gpus = sanitize_gpu_ids(gpus)
  File "/root/anaconda3/envs/transformers/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 696, in sanitize_gpu_ids    
    """)
pytorch_lightning.utilities.exceptions.MisconfigurationException:
                You requested GPUs: [0]
                But your machine only has: []
```
ex. And it may be caused by some defect for manipulating multiple GPUs:

```
(checking GPUs and whether PyTorch recognize GPUs properly:)
(transformers) root@C-7d3294a0-e709-4709-a0d3-c4022a34e24b-776:~# ls /dev/dri/
card0  card1  renderD129
(transformers) root@C-7d3294a0-e709-4709-a0d3-c4022a34e24b-776:~# rocm-smi
========================ROCm System Management Interface========================
================================================================================
GPU  Temp   AvgPwr  SCLK    MCLK    Fan     Perf  PwrCap  VRAM%  GPU%
0    30.0c  19.0W   808Mhz  350Mhz  23.92%  auto  250.0W    0%   0%
1    31.0c  17.0W   808Mhz  350Mhz  22.75%  auto  250.0W    0%   0%
================================================================================
==============================End of ROCm SMI Log ==============================
(transformers) root@C-7d3294a0-e709-4709-a0d3-c4022a34e24b-776:~# clinfo
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (3098.0)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback cl_amd_offline_devices
  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    Device 66af
  Device Topology:                               PCI[ B#103, D#0, F#0 ]
(transformers) root@C-7d3294a0-e709-4709-a0d3-c4022a34e24b-776:~# HIP_VISIBLE_DEVICES=0,1 python -c 'import torch;print(torch.cuda.device_count())' 
1


(transformers) root@C-7d3294a0-e709-4709-a0d3-c4022a34e24b-776:~# python -c "import torch; print(torch.cuda.device_count())"
1
(transformers) root@C-7d3294a0-e709-4709-a0d3-c4022a34e24b-776:~# HIP_VISIBLE_DEVICES=0 python -c "import torch; print(torch.cuda.device_count())"
1
(transformers) root@C-7d3294a0-e709-4709-a0d3-c4022a34e24b-776:~# HIP_VISIBLE_DEVICES=1 python -c "import torch; print(torch.cuda.device_count())"
0
(transformers) root@C-7d3294a0-e709-4709-a0d3-c4022a34e24b-776:~# HIP_VISIBLE_DEVICES=0,1 python -c "import torch; print(torch.cuda.device_count())"
1

```

## Expected behavior

Finishing running transformers example for training model, and recognizing GPUs properly.

## Environment

Environment the bug has occured as follows:

 - PyTorch Version (e.g., 1.0):1.60a0
 - OS (e.g., Linux):Ubuntu 18.04 
 - How you installed PyTorch (`conda`, `pip`, source):install user built wheel package via pip
 - Build command you used (if compiling from source): 
 - Python version:Python 3.7 (installing w/ conda)
 - ~CUDA/cuDNN~ ROCm version:3.3
 - GPU models and configuration:2x Radeon VII
 - Any other relevant information:Using python3 interpreter installed with Anaconda, language models using huggingface/transformers.

## Additional context

running them on cloud service.

**Comment by Delaunay** [comment]
I was able to run 8 MI50 in parallel with pytorch in the past, 
so I do not think the issue is linked directly to pytorch.
I think it is probably an issue with how the stack was installed, even clinfo only list a single device.

What kind of cloud service are you using ?
Could there be an issue with how the VM was setup ?
Maybe only one device was forwarded to it.

**Comment by Laser-Cat** [comment]
That's reminds me a while ago running two tensorflow sessions(in a single process) on two different gpus(Rx 470, Rx590) fails while running both sessions on each single GPU works just fine...

FYI:
TF version: 1.15.2, compiled from source
I used C API rather than python API. Each session is created by main thread and operated with a dedicated std::thread.
ROCM/MIOpen [Possibly] 3.3/2.3

**Comment by kazulittlefox** [comment]
Since I have found the error with the connection via CPU and GPU node 0, I would like to close this issue because it might be caused by Hardware troubles.
