### ISSUE TITLE
issue while performing the test while installing pytorch docker image

### ISSUE THREAD

**Issue by umairnsr87** [ROCmSoftwarePlatform/pytorch#671]
## Issue description

Firstly I have installed rocm. Then I am trying to install pytorch with roc docker image. Everything goes correctly .But when I run **PYTORCH_TEST_WITH_ROCM=1 python test/run_test.py --verbose** it gives me the error **No module named pytorch**. Then I tried to use **Install using minimal ROCm docker file** but it is also failing giving error **no file named cmake**.

- PyTorch or Caffe2:pytorch and caffe
- How you installed PyTorch (conda, pip, source):docker image
- Build command you used (if compiling from source):
- OS:ubuntu 16.04
- PyTorch version:
- Python version:python3
- CUDA/cuDNN version:
- GPU models and configuration: sapphire tx 580
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by jithunnair-amd** [comment]
Please make sure you're running unit tests with the same version of python that you installed pytorch for.

**Comment by umairnsr87** [comment]
Did you mean both python installed on my computer and pytorch should be same. Do you have any detailed installation guide as i am trying to sort this out from past 3 days and i am still failing.

**Comment by jithunnair-amd** [comment]
If you used one of the rocm/pytorch docker images, then you might need to specify 'python3.6' in your command line instead of 'python'. Try that and let us know if that helps.

**Comment by umairnsr87** [comment]
Let me try and check if python3 test command will work or not.

**Comment by umairnsr87** [comment]
Sorry @jithunnair-amd it is not resolved. I have tried installing it with docker image,upstream docker image too but failed getting error no module named torch.

**Comment by jithunnair-amd** [comment]
Which docker image did you use? If you use rocm/pytorch:rocm3.5_ubuntu16.04_py3.6_pytorch for eg., it should already have pytorch built in it for python3.6, and `PYTORCH_TEST_WITH_ROCM=1 python3.6 test/run_test.py --verbose` should work (at least shouldn't give the error you're seeing about importing torch).

**Comment by umairnsr87** [comment]
I am using ** rocm/pytorch:rocm3.5_ubuntu16.04_py3.6_pytorch** and this time I have run **PYTORCH_TEST_WITH_ROCM=1 python3.6 test/run_test.py --verbose** it ran this time because i was thinking my system has 3.7. But this time I got the error I am pasting the error codes below.However I got several errors in the middle but this one stopped the execution.

Here it goes...
FAIL: test_gamma_gpu_sample (__main__.TestDistributions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 699, in wrapper
    method(*args, **kwargs)
  File "test_distributions.py", line 2167, in test_gamma_gpu_sample
    failure_rate=1e-4)
  File "test_distributions.py", line 746, in _check_sampler_sampler
    self.assertLess(-threshold, bias, message)
AssertionError: -0.06743384440337652 not less than -0.068 : Gamma(alpha=0.1, beta=1.0).sample() is biased:
[ 0.032 -0.013 -0.032  0.023  0.032  0.01  -0.068 -0.011  0.001  0.026]

----------------------------------------------------------------------
Ran 214 tests in 26.789s

FAILED (failures=1)
Traceback (most recent call last):
  File "test/run_test.py", line 676, in <module>
    main()
  File "test/run_test.py", line 669, in main
    raise RuntimeError(message)
RuntimeError: test_distributions failed!

**Comment by umairnsr87** [comment]
@jithunnair-amd please help me.

**Comment by jithunnair-amd** [comment]
This test (and all unit tests) are passing in our CI runs with gfx900 and gfx906. Can you verify which GPU architecture you're running on? You can get that info using something like: `rocminfo | egrep "^  Name:"`

**Comment by umairnsr87** [comment]
ROCk module is loaded
Able to open /dev/kfd read-write
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 5 2600 Six-Core Processor
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 5 2600 Six-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3400                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            12                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    8180732(0x7cd3fc) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    8180732(0x7cd3fc) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 2                  
*******                  
  Name:                    gfx803                             
  Uuid:                    GPU-XX                             
  Marketing Name:          Ellesmere [Radeon RX 470/480/570/570X/580/580X]
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26591(0x67df)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1366                               
  BDFID:                   2304                               
  Internal Node ID:        1                                  
  Compute Unit:            36                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    8388608(0x800000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx803          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32

**Comment by umairnsr87** [comment]
@jithunnair-amd  its gfx803

**Comment by jithunnair-amd** [comment]
@sunway513 Any comments on gfx803?

**Comment by sunway513** [comment]
Pytorch unit tests are not covered by QA or public PyTorch CI, hence we have less coverage for the gfx803 target for unit tests.

**Comment by umairnsr87** [comment]
what should I do now? This is making me regret my decision to buy this gpu.

**Comment by sunway513** [comment]
Hi @umairnsr87 , for computing I'd suggest to go with Vega10 or Vega20 based GPUs, as we have comprehensive CI coverage on those GPU architectures for PyTorch. 
What we can do for gfx803 is quite limited right now due to resources available. However, passing all unit tests are not the prerequisite to run a particular DL workloads.

**Comment by umairnsr87** [comment]
@sunway513 i have already purchased if a few days back.

**Comment by umairnsr87** [comment]
Did you mean even if the test fails i can still use the gpus for dl ?

**Comment by sunway513** [comment]
Correct, feel free to try the PT workloads you care about.
