### ISSUE TITLE
run jupyter no kernels

### ISSUE THREAD

**Issue by liygzting** [ROCmSoftwarePlatform/pytorch#706]
## To Reproduce

1.sudo docker run -it -v $HOME:/data --privileged --rm --device=/dev/kfd --device=/dev/dri --group-add video -p 18888:8888 rocm/pytorch:rocm3.5_ubuntu16.04_py3.6_pytorch
2.jupyter notebook --ip 0.0.0.0 --no-browser --allow-root

[I 13:17:30.249 NotebookApp] Serving notebooks from local directory: /root
[I 13:17:30.249 NotebookApp] The Jupyter Notebook is running at:
[I 13:17:30.249 NotebookApp] http://aad31bea8ba5:8888/?token=3b345fdd338cadd4460ed9bbf8719f22ae32ce0b18eafc01
[I 13:17:30.249 NotebookApp]  or http://127.0.0.1:8888/?token=3b345fdd338cadd4460ed9bbf8719f22ae32ce0b18eafc01
[I 13:17:30.249 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:17:30.252 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/nbserver-17016-open.html
    Or copy and paste one of these URLs:
        http://aad31bea8ba5:8888/?token=3b345fdd338cadd4460ed9bbf8719f22ae32ce0b18eafc01
     or http://127.0.0.1:8888/?token=3b345fdd338cadd4460ed9bbf8719f22ae32ce0b18eafc01

## Expected behavior
local browser can get http://127.0.0.1:18888/?token=3b345fdd338cadd4460ed9bbf8719f22ae32ce0b18eafc01
but i cann't do anything for python3

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by briansp2020** [comment]
I usually do

>docker run -it -v $HOME:/root/bsp2020 --privileged --network=host --ipc=host --device=/dev/kfd --device=/dev/dri --group-add video

That way, the container shares the ports of the host. If you want to export only a specific port, I think you have to expose as well as publishing. See https://nickjanetakis.com/blog/docker-tip-59-difference-between-exposing-and-publishing-ports#:~:text=You%20can%20expose%20a%20port,%2Dp%2080%3A80%20flag.

So in your case,
>sudo docker run -it -v $HOME:/data --privileged --rm --device=/dev/kfd --device=/dev/dri --group-add video --expose 8888 -p 18888:8888 rocm/pytorch:rocm3.5_ubuntu16.04_py3.6_pytorch

**Comment by liygzting** [comment]
thanks @briansp2020 
I can be in jupyter whether it's your way or mine
but my confusion is that the container cannot create a new python3 after it enters
As shown below
![image](https://user-images.githubusercontent.com/35652426/89722457-22712000-da1c-11ea-8b67-39995964b245.png)

**Comment by lcskrishna** [comment]
@liygzting Can you try running ```pip3.6 install notebook``` inside the docker and then launch the jupyter notebook

**Comment by liygzting** [comment]
> @liygzting Can you try running `pip3.6 install notebook` inside the docker and then launch the jupyter notebook

yes   thanks @lcskrishna 
Due to lack of components
![image](https://user-images.githubusercontent.com/35652426/89730428-f6cc5500-da70-11ea-8a33-49c228d5ed4d.png)
