### ISSUE TITLE
Expecting a  prebuild version on PYPI for pytorch instead of using Docker

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/pytorch#716]
Unlike Tensorflow, for pytorch, there is only docker version, but it limits the python version and other linux software version, so that it cannot meet many custom environment restrictions when integrating pytorch-rocm with other applications.

So looking forward to a prebuild version on PYPI for pytorch instead of using Docker.

**Comment by sunway513** [comment]
Hi @ghostplant , thanks for the post! Yes, this is in our planning, we will let you know once we have more to update.

**Comment by boniek83** [comment]
Don't forget to integrate it with anaconda as well :)

**Comment by ghostplant** [comment]
@sunway513 Is there any issues blocking this? https://github.com/pypa/pypi-support/issues/48
I think pip link can also be a web link provided by official AMD if public PYPI has many restrictions.

Like what pytorch-cuda has done:
```sh
Style-1: Manage a repo
pip3 install torch==1.5.0 torchvision==0.6.0 -f https://download.pytorch.org/whl/torch_stable.html
```
```sh
Style-2: Provide wheel link
pip3 install https://download.pytorch.org/whl/cu92/torch-1.6.0%2Bcu92-cp36-cp36m-linux_x86_64.whl
```

**Comment by sunway513** [comment]
Hi @ghostplant , we have so far enabled nightly whl packages for PyTorch, you can use the following command to deploy the PyTorch nightly whls from PyTorch official, e.g. with ROCm4.0:
`pip3 install --pre torch -f https://download.pytorch.org/whl/nightly/rocm4.0/torch_nightly.html`
We're working towards more deployment options, I'll keep this thread updated once I have more to update.

**Comment by sunway513** [comment]
Hi @ghostplant , we've pushed out the python3.8 based 1.16 WHL package, please check it out and let us know if you see issues.
Command to install with ROCm4.0 environment:
`pip install tensorflow-rocm==1.15.9` for regular release
`pip install tensorflow-rocm-enhanced==1.15.5` for the enhanced release. 

Moving forward we'll release the python3.8 based whl with TF1.15 for the future ROCm releases, for the details on the compatibility info, please refer to this doc:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md

**Comment by ghostplant** [comment]
Thanks. It is solved. I'll close this issue.

**Comment by sunway513** [comment]
The whl package installation information can be found from pytorch.org as well.
