### ISSUE TITLE
build against hipMagma to enable Tensor.cuda().inverse()

### ISSUE THREAD

**Issue by flowpoint** [ROCmSoftwarePlatform/pytorch#738]
## 🚀 Feature

building against magma to enable Tensor.cuda().inverse()

## Motivation

some models use torch.Tensor.inverse() on gpu,
it is required for code like [Waveglow](https://pytorch.org/hub/nvidia_deeplearningexamples_tacotron2/) and its [Invertible1x1Conv](https://github.com/NVIDIA/DeepLearningExamples/blob/b2e89e6e80ca27b3a030d6419ba13a7022c869f3/PyTorch/SpeechSynthesis/Tacotron2/waveglow/model.py#L83)

## Pitch

i want this kind of snippet to work on rocm pytorch (efficiently):
``` 
import torch
a = torch.tensor([[-3, 1],[5,0]])
a.cuda().inverse()
```

## Alternatives

my temporary workaround or inelegant solution is:
` a.cpu().inverse().cuda()`

## Additional context

running it on cpu, doesnt seem to be bottlenecking waveglow (yet, still investigating performance issues)

this functionality is missing in the docker container:
docker.io/rocm/pytorch:latest
and throws a magma not found error

**Comment by flowpoint** [comment]
i just recognized that magma supports hip and is not nvidia specific.
updating the request accordingly

**Comment by sunway513** [comment]
@jeffdaily  can you review this issue as we now have hipMagma support merged in upstream PyTorch repo?

**Comment by sunway513** [comment]
Hi @flowpoint we now have preliminary hipMagma integration with the official PyTorch 1.8 release. 
You can refer to the "Start Locally" instructions to install the ROCm4.0.1 PyTorch 1.8 whl package and test:
https://pytorch.org/get-started/locally/

**Comment by 401qingkong** [comment]
I want to compile ROCm pytorch with the hipMagma library from source， could you give me some advice about how to do it. Now I have tried to compile pytorch with hipMagma branch hipMAGMAv2.0.0 download from this link [https://bitbucket.org/icl/magma/src/hipMAGMAv2.0.0/]  in ROCm 3.9 env ,but finally a torch link error occures as follows:
libtorch_hip.so: undefined reference to `magma_strsm_v1'.

could you give me some advice? or do you have  a rocm pytorch branch intergrated with hipMagma that support us  to download and compile from src?

**Comment by sunway513** [comment]
cc @amathews-amd @rraminen can you help? Thanks..

**Comment by amathews-amd** [comment]
Hi @401qingkong , 
For building from source, could you follow the instructions in https://github.com/pytorch/pytorch/blob/master/.circleci/docker/common/install_rocm.sh#L5 for installing MAGMA ? 

The wheels build for pytorch rocm should have the already compiled MAGMA library. 
pip3 install torch -f https://download.pytorch.org/whl/rocm4.0.1/torch_stable.html
pip3 install ninja && pip3 install 'git+https://github.com/pytorch/vision.git@v0.9.1'
(from https://pytorch.org/get-started/locally/ )

**Comment by 401qingkong** [comment]
@amathews-amd I compile and install hipMAGMA just follows the instrctions you referred in the above link. And  I compile pytorch with USE_MAGMA=1, But the torch link error still occures as follows:
libtorch_hip.so: undefined reference to `magma_strsm_v1'.
libtorch_hip.so: undefined reference to `magma_dtrsm_v1'

**Comment by amathews-amd** [comment]
You need latest ROCm. ROCm4.1 and above should work. The earlier versions of pytorch was integrated with a branch of hipMagma, that does not exist anymore.
