### ISSUE TITLE
hipErrorNoBinaryForGpu on Ryzen 7 4800U

### ISSUE THREAD

**Issue by xperroni** [ROCmSoftwarePlatform/pytorch#786]
## 🐛 Bug

Trying to run PyTorch on a Ryzen 7 4800U system from Docker image `rocm/pytorch:rocm4.0_ubuntu18.04_py3.6_pytorch` fails with error `hipErrorNoBinaryForGpu`. Previous image versions (e.g. `rocm/pytorch:rocm3.8_ubuntu18.04_py3.6_pytorch`) worked fine.

## To Reproduce

1. [Setup the host environment](https://rocmdocs.amd.com/en/latest/Deep_learning/Deep-learning.html#pytorch)
2. `docker pull rocm/pytorch:rocm4.0_ubuntu18.04_py3.6_pytorch`
3. `docker run -it -v $HOME:/data --privileged --rm --device=/dev/kfd --device=/dev/dri --group-add video rocm/pytorch:rocm4.0_ubuntu18.04_py3.6_pytorch`
4. `PYTORCH_TEST_WITH_ROCM=1 python test/run_test.py`

This fails with:

    /src/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
    Aborted (core dumped)

## Expected behavior

Test script should run successfully.

## Environment

Host:

    Collecting environment information...
    PyTorch version: N/A
    Is debug build: N/A
    CUDA used to build PyTorch: N/A
    ROCM used to build PyTorch: N/A

    OS: Ubuntu 18.04.5 LTS (x86_64)
    GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    Clang version: Could not collect
    CMake version: Could not collect

    Python version: 3.6 (64-bit runtime)
    Is CUDA available: N/A
    CUDA runtime version: Could not collect
    GPU models and configuration: Could not collect
    Nvidia driver version: Could not collect
    cuDNN version: Could not collect
    HIP runtime version: N/A
    MIOpen runtime version: N/A

    Versions of relevant libraries:
    [pip] Could not collect
    [conda] Could not collect

Image `rocm/pytorch:rocm3.8_ubuntu18.04_py3.6_pytorch`:

    Collecting environment information...
    PyTorch version: 1.7.0a0+fc1103a
    Is debug build: False
    CUDA used to build PyTorch: N/A
    ROCM used to build PyTorch: 3.8.20371-d1886b0b

    OS: Ubuntu 18.04.4 LTS (x86_64)
    GCC version: Could not collect
    Clang version: Could not collect
    CMake version: version 3.6.3

    Python version: 3.6 (64-bit runtime)
    Is CUDA available: True
    CUDA runtime version: Could not collect
    GPU models and configuration: Device 1636
    Nvidia driver version: Could not collect
    cuDNN version: Could not collect
    HIP runtime version: 3.18.6
    MIOpen runtime version: 2.6.0

    Versions of relevant libraries:
    [pip3] numpy==1.18.5
    [pip3] torch==1.7.0a0+fc1103a
    [pip3] torchvision==0.8.0a0+ac3ba94
    [conda] Could not collect

Image `rocm/pytorch:rocm4.0_ubuntu18.04_py3.6_pytorch`:

    /src/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")

## Additional context

Computer is an ASUS PN50 Ryzen 7 4800U system.

Running `rocminfo` from the `rocm/pytorch:rocm3.8_ubuntu18.04_py3.6_pytorch` image identifies the GPU as a `gfx900`, while in the image `rocm/pytorch:rocm4.0_ubuntu18.04_py3.6_pytorch` it's identified as a `gfx902`.

**Comment by xuhuisheng** [comment]
`{ 0x1636, 9, 0, 2, "Renoir", CHIP_RENOIR }`
1636 is renoir gfx902, which is not supported by ROCm.

Now only gfx900, gfx906, gfx908 had offical support on ROCm.

**Comment by xperroni** [comment]
> `{ 0x1636, 9, 0, 2, "Renoir", CHIP_RENOIR }`
> 1636 is renoir gfx902, which is not supported by ROCm.
> 
> Now only gfx900, gfx906, gfx908 had offical support on ROCm.

What's weird is that if I run `rocminfo` on the `rocm/pytorch:rocm3.8_ubuntu18.04_py3.6_pytorch` image, it detects the on-chip GPU as a `gfx900`:

    *******                  
    Agent 2                  
    *******                  
      Name:                    gfx900

...which kind of makes me hopeful that if only I could get the `gfx902` (mis-)detected as a `gfx900`, it would still work.

**Comment by sunway513** [comment]
Hi @xperroni , like the previous comment, ROCm doesn't official support gfx902 iGPU at this moment. 
I'll close this issue for now, if you need further assistance please create issues on the main ROCm github repo:
https://github.com/RadeonOpenCompute/ROCm/issues
