### ISSUE TITLE
Memory access fault by GPU node-2 (Agent handle: 0x56468ab3bb50) on address 0x7fe55fb03000. Reason: Page not present or supervisor p rivilege.Aborted (core dumped)

### ISSUE THREAD

**Issue by dshm** [ROCmSoftwarePlatform/pytorch#797]
Docker image tried: rocm/pytorch:rocm4.0_ubuntu18.04_py3.6_pytorch_1.7.0  and  rocm/pytorch:latest

card:[AMD/ATI] Vega 10 [Radeon PRO WX 8100], rocminfo is shown below
Agent 3                  
*******                  
  Name:                    gfx900                             
  Uuid:                    GPU-021544ce42504164               
  Marketing Name:          Device 6868                        
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    2                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26728(0x6868)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1500                               
  BDFID:                   15616                              
  Internal Node ID:        2                                  
  Compute Unit:            56                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    8372224(0x7fc000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx900          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                       

source code tested: https://github.com/pytorch/examples master branch, commit id c8423c8e83b64ac991cf29022344db59dd0fe497, I try the word_language_model example and run python main.py --cuda --epochs 6    also，I try imagenet example and run python main.py -a resnet18 -b 32 /imagenet   the imagenet data is saved in /imagenet folder, both example breakdown as Memory access fault by GPU node-2 (Agent handle: 0x56468ab3bb50) on address 0x7fe55fb03000. Reason: Page not present or supervisor p rivilege.Aborted (core dumped)

I have tried many ways to solve the problem, such compile the source code, update to the lastest docker image  and etc. but none worked.
I also tried  https://github.com/ROCmSoftwarePlatform/examples.git, it gives the same error.
Could someone please give me some advice? Thanks!

**Comment by sunway513** [comment]
Hi @dshm , from your description the issue should be system configuration related. 
I'd suggest you to create an issue in the ROCm repo and use HIP examples to reproduce the issue:
https://github.com/ROCm-Developer-Tools/HIP-Examples
https://github.com/RadeonOpenCompute/ROCm/issues

Once you're able to execute the HIP examples, please reopen the this issue and we can try PyTorch from there, thanks.
