### ISSUE TITLE
"undefined symbol: _ZN3tbb4task13note_affinityEt" while running mlperf DLRM model with PyTorch+MKLDNN+MKL built with TBB

### ISSUE THREAD

**Issue by shrutiramesh1988** [ROCmSoftwarePlatform/pytorch#816]
## To Reproduce

1.conda install tbb
2. USE_ROCM=0 **MKL_THREADING=TBB MKLDNN_THREADING=TBB** BLAS=MKL USE_MKLDNN=1 **MKL_TBB=1 USE_TBB=1 ATEN_THREADING=TBB** python setup.py install

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.7.0a0+ca81caf
 - OS (e.g., Linux): Ubuntu 18.04.5 LTS
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source): USE_ROCM=0 **MKL_THREADING=TBB MKLDNN_THREADING=TBB** BLAS=MKL USE_MKLDNN=1 **MKL_TBB=1 USE_TBB=1 ATEN_THREADING=TBB** python setup.py install
 - Python version: 3.8.8
 - CUDA/cuDNN version: Not using CUDA
 - GPU models and configuration: N.A.
 - Any other relevant information:

**Comment by jeffdaily** [comment]
Is this specific to ROCm PyTorch fork?  Or can it be reproduced using upstream master?  If so, please submit the bug report to upstream.

**Comment by shrutiramesh1988** [comment]
This issue is not seen with the master branch of ROCm PyTorch or upstream PyTorch. Seems to be specific to version PyTorch1.7.

**Comment by jithunnair-amd** [comment]
@shrutiramesh1988 So this error is with upstream PyTorch repo and release/1.7 branch?

**Comment by shrutiramesh1988** [comment]
We verified that this issue is not seen with the master branch of ROCm PyTorch : https://github.com/ROCmSoftwarePlatform/pytorch.git

We have also verified that the issue is not seen with the master branch of mainstream PyTorch : https://github.com/pytorch/pytorch.git

However, this issue is observed with release/1.7 branch of ROCm PyTorch : https://github.com/ROCmSoftwarePlatform/pytorch/tree/release/1.7

I will close this issue as the latest master branch is working fine.
