### ISSUE TITLE
unskip distributed test_leak.py

### ISSUE THREAD

**Issue by pruthvistony** [ROCmSoftwarePlatform/pytorch#941]
### 🐛 Describe the bug

distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[always-eval]
distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[always-train]
distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[except_last-eval]
distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[except_last-train]
distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[never-eval]
distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[never-train]
distributed/pipeline/sync/skip/test_leak.py::test_no_portal_without_pipe[eval]
distributed/pipeline/sync/skip/test_leak.py::test_no_portal_without_pipe[train]

### Versions

ROCm version: 4.5.2
PyTorch commit: https://github.com/pytorch/pytorch/commit/4b4f652f799c732a7280052e44a803a4cf6084de
March 17, 2022
Test Audit logs
ROCm Test1: https://ossci-raw-job-status.s3.amazonaws.com/log/5590875721
ROCm Test2: https://ossci-raw-job-status.s3.amazonaws.com/log/5590875831
ROCm distributed tests: https://ossci-raw-job-status.s3.amazonaws.com/log/5590691830
CUDA Test1: https://ossci-raw-job-status.s3.amazonaws.com/log/5590724129
CUDA Test2: https://ossci-raw-job-status.s3.amazonaws.com/log/5590724019
CUDA distributed tests: https://ossci-raw-job-status.s3.amazonaws.com/log/5590723920

**Comment by ChaithanyaVenumuddala** [comment]
These tests are already enabled and passing on RoCm 5.0
distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[always-train] PASSED [ 12%]
distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[always-eval] PASSED [ 25%]
distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[except_last-train] PASSED [ 37%]
distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[except_last-eval] PASSED [ 50%]
distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[never-train] PASSED [ 62%]
distributed/pipeline/sync/skip/test_leak.py::test_delete_portal_tensor[never-eval] PASSED [ 75%]
distributed/pipeline/sync/skip/test_leak.py::test_no_portal_without_pipe[train] PASSED [ 87%]
distributed/pipeline/sync/skip/test_leak.py::test_no_portal_without_pipe[eval] PASSED [100%]
