### ISSUE TITLE
unskip distributed test_bugs.py

### ISSUE THREAD

**Issue by pruthvistony** [ROCmSoftwarePlatform/pytorch#943]
### 🐛 Describe the bug

distributed/pipeline/sync/test_bugs.py::test_exception_no_hang
distributed/pipeline/sync/test_bugs.py::test_parallel_randoms
distributed/pipeline/sync/test_bugs.py::test_python_autograd_function

### Versions

ROCm version: 4.5.2
PyTorch commit: https://github.com/pytorch/pytorch/commit/4b4f652f799c732a7280052e44a803a4cf6084de
March 17, 2022
Test Audit logs
ROCm Test1: https://ossci-raw-job-status.s3.amazonaws.com/log/5590875721
ROCm Test2: https://ossci-raw-job-status.s3.amazonaws.com/log/5590875831
ROCm distributed tests: https://ossci-raw-job-status.s3.amazonaws.com/log/5590691830
CUDA Test1: https://ossci-raw-job-status.s3.amazonaws.com/log/5590724129
CUDA Test2: https://ossci-raw-job-status.s3.amazonaws.com/log/5590724019
CUDA distributed tests: https://ossci-raw-job-status.s3.amazonaws.com/log/5590723920

**Comment by ChaithanyaVenumuddala** [comment]
These tests are already enabled and passing on RoCm 5.0

distributed/pipeline/sync/test_bugs.py::test_python_autograd_function PASSED [ 25%]
distributed/pipeline/sync/test_bugs.py::test_exception_no_hang PASSED    [ 50%]
distributed/pipeline/sync/test_bugs.py::test_tuple_wait PASSED           [ 75%]
distributed/pipeline/sync/test_bugs.py::test_parallel_randoms PASSED     [100%]
