### ISSUE TITLE
unskip distributed test_pipe.py

### ISSUE THREAD

**Issue by pruthvistony** [ROCmSoftwarePlatform/pytorch#946]
### 🐛 Describe the bug

distributed/pipeline/sync/test_pipe.py::test_batch_size_indivisible
distributed/pipeline/sync/test_pipe.py::test_batch_size_small
distributed/pipeline/sync/test_pipe.py::test_checkpoint_eval
distributed/pipeline/sync/test_pipe.py::test_checkpoint_mode
distributed/pipeline/sync/test_pipe.py::test_checkpoint_mode_invalid
distributed/pipeline/sync/test_pipe.py::test_checkpoint_mode_when_chunks_1
distributed/pipeline/sync/test_pipe.py::test_checkpoint_non_float_input
distributed/pipeline/sync/test_pipe.py::test_chunks_less_than_1
distributed/pipeline/sync/test_pipe.py::test_deferred_batch_norm[always]
distributed/pipeline/sync/test_pipe.py::test_deferred_batch_norm[except_last]
distributed/pipeline/sync/test_pipe.py::test_deferred_batch_norm[never]
distributed/pipeline/sync/test_pipe.py::test_deferred_batch_norm_params[always]
distributed/pipeline/sync/test_pipe.py::test_deferred_batch_norm_params[never]
distributed/pipeline/sync/test_pipe.py::test_deny_moving
distributed/pipeline/sync/test_pipe.py::test_devices
distributed/pipeline/sync/test_pipe.py::test_empty_module
distributed/pipeline/sync/test_pipe.py::test_exception
distributed/pipeline/sync/test_pipe.py::test_exception_early_stop_asap
distributed/pipeline/sync/test_pipe.py::test_forward_lockstep
distributed/pipeline/sync/test_pipe.py::test_input_pair
distributed/pipeline/sync/test_pipe.py::test_input_singleton
distributed/pipeline/sync/test_pipe.py::test_input_varargs
distributed/pipeline/sync/test_pipe.py::test_inputs_wrong_device
distributed/pipeline/sync/test_pipe.py::test_merged_partitions
distributed/pipeline/sync/test_pipe.py::test_multi_sequence_input
distributed/pipeline/sync/test_pipe.py::test_multiple_inputs[always]
distributed/pipeline/sync/test_pipe.py::test_multiple_inputs[except_last]
distributed/pipeline/sync/test_pipe.py::test_multiple_inputs[never]
distributed/pipeline/sync/test_pipe.py::test_named_children
distributed/pipeline/sync/test_pipe.py::test_nested_input
distributed/pipeline/sync/test_pipe.py::test_no_chunk[always]
distributed/pipeline/sync/test_pipe.py::test_no_chunk[except_last]
distributed/pipeline/sync/test_pipe.py::test_no_chunk[never]
distributed/pipeline/sync/test_pipe.py::test_no_grad
distributed/pipeline/sync/test_pipe.py::test_no_tensor_output[always]
distributed/pipeline/sync/test_pipe.py::test_no_tensor_output[except_last]
distributed/pipeline/sync/test_pipe.py::test_no_tensor_output[never]
distributed/pipeline/sync/test_pipe.py::test_non_tensor
distributed/pipeline/sync/test_pipe.py::test_non_tensor_sequence
distributed/pipeline/sync/test_pipe.py::test_parameters
distributed/pipeline/sync/test_pipe.py::test_partitions
distributed/pipeline/sync/test_pipe.py::test_public_attrs
distributed/pipeline/sync/test_pipe.py::test_sequential_like
distributed/pipeline/sync/test_pipe.py::test_uneven_batch_size[always]
distributed/pipeline/sync/test_pipe.py::test_uneven_batch_size[except_last]
distributed/pipeline/sync/test_pipe.py::test_uneven_batch_size[never]
distributed/pipeline/sync/test_pipe.py::test_valid_non_tensor[always]
distributed/pipeline/sync/test_pipe.py::test_valid_non_tensor[except_last]
distributed/pipeline/sync/test_pipe.py::test_valid_non_tensor[never]
distributed/pipeline/sync/test_pipe.py::test_verify_module_duplicate_children
distributed/pipeline/sync/test_pipe.py::test_verify_module_duplicate_parameters_on_same_device
distributed/pipeline/sync/test_pipe.py::test_verify_module_non_sequential
distributed/pipeline/sync/test_pipe.py::test_verify_module_params_on_same_device
distributed/pipeline/sync/test_pipe.py::test_verify_nested_modules
distributed/pipeline/sync/test_pipe.py::test_with_device_wrapper

### Versions

ROCm version: 4.5.2
PyTorch commit: https://github.com/pytorch/pytorch/commit/4b4f652f799c732a7280052e44a803a4cf6084de
March 17, 2022
Test Audit logs
ROCm Test1: https://ossci-raw-job-status.s3.amazonaws.com/log/5590875721
ROCm Test2: https://ossci-raw-job-status.s3.amazonaws.com/log/5590875831
ROCm distributed tests: https://ossci-raw-job-status.s3.amazonaws.com/log/5590691830
CUDA Test1: https://ossci-raw-job-status.s3.amazonaws.com/log/5590724129
CUDA Test2: https://ossci-raw-job-status.s3.amazonaws.com/log/5590724019
CUDA distributed tests: https://ossci-raw-job-status.s3.amazonaws.com/log/5590723920

**Comment by ChaithanyaVenumuddala** [comment]
These tests are already enabled and passing on RoCm 5.0

distributed/pipeline/sync/test_pipe.py::test_pipe_without_rpc PASSED     [  1%]
distributed/pipeline/sync/test_pipe.py::test_parameters PASSED           [  3%]
distributed/pipeline/sync/test_pipe.py::test_public_attrs PASSED         [  5%]
distributed/pipeline/sync/test_pipe.py::test_sequential_like PASSED      [  7%]
distributed/pipeline/sync/test_pipe.py::test_chunks_less_than_1 PASSED   [  8%]
distributed/pipeline/sync/test_pipe.py::test_batch_size_indivisible PASSED [ 10%]
distributed/pipeline/sync/test_pipe.py::test_batch_size_small PASSED     [ 12%]
distributed/pipeline/sync/test_pipe.py::test_checkpoint_mode PASSED      [ 14%]
distributed/pipeline/sync/test_pipe.py::test_checkpoint_mode_invalid PASSED [ 16%]
distributed/pipeline/sync/test_pipe.py::test_checkpoint_mode_when_chunks_1 PASSED [ 17%]
distributed/pipeline/sync/test_pipe.py::test_checkpoint_eval PASSED      [ 19%]
distributed/pipeline/sync/test_pipe.py::test_checkpoint_non_float_input PASSED [ 21%]
distributed/pipeline/sync/test_pipe.py::test_no_grad PASSED              [ 23%]
distributed/pipeline/sync/test_pipe.py::test_exception PASSED            [ 25%]
distributed/pipeline/sync/test_pipe.py::test_exception_early_stop_asap PASSED [ 26%]
distributed/pipeline/sync/test_pipe.py::test_nested_input PASSED         [ 28%]
distributed/pipeline/sync/test_pipe.py::test_input_pair PASSED           [ 30%]
distributed/pipeline/sync/test_pipe.py::test_multi_sequence_input PASSED [ 32%]
distributed/pipeline/sync/test_pipe.py::test_input_singleton PASSED      [ 33%]
distributed/pipeline/sync/test_pipe.py::test_input_varargs PASSED        [ 35%]
distributed/pipeline/sync/test_pipe.py::test_non_tensor PASSED           [ 37%]
distributed/pipeline/sync/test_pipe.py::test_non_tensor_sequence PASSED  [ 39%]
distributed/pipeline/sync/test_pipe.py::test_valid_non_tensor[never] PASSED [ 41%]
distributed/pipeline/sync/test_pipe.py::test_valid_non_tensor[always] PASSED [ 42%]
distributed/pipeline/sync/test_pipe.py::test_valid_non_tensor[except_last] PASSED [ 44%]
distributed/pipeline/sync/test_pipe.py::test_no_tensor_output[never] PASSED [ 46%]
distributed/pipeline/sync/test_pipe.py::test_no_tensor_output[always] PASSED [ 48%]
distributed/pipeline/sync/test_pipe.py::test_no_tensor_output[except_last] PASSED [ 50%]
distributed/pipeline/sync/test_pipe.py::test_uneven_batch_size[never] PASSED [ 51%]
distributed/pipeline/sync/test_pipe.py::test_uneven_batch_size[always] PASSED [ 53%]
distributed/pipeline/sync/test_pipe.py::test_uneven_batch_size[except_last] PASSED [ 55%]
distributed/pipeline/sync/test_pipe.py::test_no_chunk[never] PASSED      [ 57%]
distributed/pipeline/sync/test_pipe.py::test_no_chunk[always] PASSED     [ 58%]
distributed/pipeline/sync/test_pipe.py::test_no_chunk[except_last] PASSED [ 60%]
distributed/pipeline/sync/test_pipe.py::test_deferred_batch_norm[never] PASSED [ 62%]
distributed/pipeline/sync/test_pipe.py::test_deferred_batch_norm[always] PASSED [ 64%]
distributed/pipeline/sync/test_pipe.py::test_deferred_batch_norm[except_last] PASSED [ 66%]
distributed/pipeline/sync/test_pipe.py::test_deferred_batch_norm_params[never] PASSED [ 67%]
distributed/pipeline/sync/test_pipe.py::test_deferred_batch_norm_params[always] PASSED [ 69%]
distributed/pipeline/sync/test_pipe.py::test_devices PASSED              [ 71%]
distributed/pipeline/sync/test_pipe.py::test_partitions PASSED           [ 73%]
distributed/pipeline/sync/test_pipe.py::test_merged_partitions PASSED    [ 75%]
distributed/pipeline/sync/test_pipe.py::test_deny_moving PASSED          [ 76%]
distributed/pipeline/sync/test_pipe.py::test_empty_module PASSED         [ 78%]
distributed/pipeline/sync/test_pipe.py::test_named_children PASSED       [ 80%]
distributed/pipeline/sync/test_pipe.py::test_verify_module_non_sequential PASSED [ 82%]
distributed/pipeline/sync/test_pipe.py::test_verify_module_duplicate_children PASSED [ 83%]
distributed/pipeline/sync/test_pipe.py::test_verify_module_params_on_same_device PASSED [ 85%]
distributed/pipeline/sync/test_pipe.py::test_verify_nested_modules PASSED [ 87%]
distributed/pipeline/sync/test_pipe.py::test_verify_module_duplicate_parameters_on_same_device PASSED [ 89%]
distributed/pipeline/sync/test_pipe.py::test_forward_lockstep PASSED     [ 91%]
distributed/pipeline/sync/test_pipe.py::test_multiple_inputs[never] PASSED [ 92%]
distributed/pipeline/sync/test_pipe.py::test_multiple_inputs[always] PASSED [ 94%]
distributed/pipeline/sync/test_pipe.py::test_multiple_inputs[except_last] PASSED [ 96%]
distributed/pipeline/sync/test_pipe.py::test_inputs_wrong_device PASSED  [ 98%]
distributed/pipeline/sync/test_pipe.py::test_with_device_wrapper PASSED  [100%]
