### ISSUE TITLE
unskip distributed/pipeline/sync/test_transparency 

### ISSUE THREAD

**Issue by amathews-amd** [ROCmSoftwarePlatform/pytorch#960]
### 🐛 Describe the bug

distributed/pipeline/sync/test_transparency | distributed/pipeline/sync/test_transparency.py::test_simple_linears |  
-- | -- | --

### Versions

ROCm version: 4.5.2
PyTorch commit: https://github.com/pytorch/pytorch/commit/4b4f652f799c732a7280052e44a803a4cf6084de
March 17, 2022
Test Audit logs
ROCm Test1: https://ossci-raw-job-status.s3.amazonaws.com/log/5590875721
ROCm Test2: https://ossci-raw-job-status.s3.amazonaws.com/log/5590875831
ROCm distributed tests: https://ossci-raw-job-status.s3.amazonaws.com/log/5590691830
CUDA Test1: https://ossci-raw-job-status.s3.amazonaws.com/log/5590724129
CUDA Test2: https://ossci-raw-job-status.s3.amazonaws.com/log/5590724019
CUDA distributed tests: https://ossci-raw-job-status.s3.amazonaws.com/log/5590723920

**Comment by ChaithanyaVenumuddala** [comment]
The test is already enabled and passed on RoCm 5.0

distributed/pipeline/sync/test_transparency.py::test_simple_linears PASSED [100%]
